<?php
if (!defined('BASEPATH')) exit('You Have Not Permission To access');

	class Settings extends CI_Controller
	{
		
		public function __construct(){
			parent:: __construct();
			$this->permission->is_logged_in(); 
			$this->permission->clear_cache();
			$this->load->model('Settings_model'); 
			define('VARIABLE_QUANTITY',6);	
		}
		
		public function setDateOfBirth(){
			//get the emplyees
			$employees = $this->Settings_model->getAll('newosi');
			$update_array = [];
			//iterate over them
			foreach($employees as $k=>$employee){
				//get the dob
				$dob = $employee->dateofbith;
				//set the date
				$dobnew = $this->convertDateToCorrectFormat(trim($dob));
					//create the update batch
				$update_array[] = 
				   [
					  'dateofbirth' => $dobnew ,
					  'man_id'  => $employee->man_id,
					  
				   ];
			}
			$this->Settings_model->update('newosi',$update_array,'man_id');
			//$this->db->updateBatch($update_array, 'man_id');
			//echo 'hi';
			//update the batch
		}
		function convertDateToCorrectFormat($in_date){
			$out_date = NULL;
			if($in_date==''){
				$out_date = NULL;
			}elseif(preg_match('/^(0[1-9]|[1-2][0-9]|3[0-1]|[1-9])\/([1-9]|0[1-9]|1[0-2])\/[0-9]{4}$/',$in_date)){			//dd/mm/yyyy d/m/yyyy
				$date = date_create_from_format('d/m/Y',$in_date);
				$out_date = date_format($date,'Y-m-d');
			}elseif(preg_match('/^([1-9]|0[1-9]|1[0-2])\/(0[1-9]|1[0-9]|2[0-9]|3[0-1]|[1-9])\/([0-9]{4})$/',$in_date)){		//mm/dd/yyyy  and m/d/yyyy
				$date = date_create_from_format('m/d/Y',$in_date);
				$out_date = date_format($date,'Y-m-d');
			}elseif(preg_match('/^(0[1-9]|1[0-9]|2[0-9]|3[0-1]|[1-9])-([1-9]|0[1-9]|1[0-2])-[0-9]{4}$/',$in_date)){				//dd-mm-yyyy  and d-m-yyyy
				$date = date_create_from_format('d-m-Y',$in_date);
				$out_date = date_format($date,'Y-m-d');
			}elseif(preg_match('/^([1-9]|0[1-9]|1[0-2])-([1-9]|0[1-9]|1[0-9]|2[0-9]|3[0-1])-([0-9]{4})$/',$in_date)){		//mm-dd-yyyy  and m-d-yyyy
				$date = date_create_from_format('m-d-Y',$in_date);
				$out_date = date_format($date,'Y-m-d');
			}else{
				$out_date = $in_date;
			}
			return $out_date;
		}


		public function allUsersExcel(){
			$this->load->model('Osi_model');
			$this->load->helper('common_helper');
			$default_cols = array('newosi.man_id','newosi.name as empName','presentrank','depttno','dateofbith','dateofinlitment','newosi.bat_id','dateofretirment','dateofinlitment','dateofretirment','eduqalification','ierank','phono1','district','gender','maritalstatus','caste','category','bloodgroup','comlit','ono');
			$selected_columns = array();
			if(null!=$this->input->post('columns')){
				$cols = array_keys($this->input->post('columns'));
				if(null!=$cols && !empty($cols)){
					$columns = $cols;
				}else{
					$columns = $default_cols;
				}
			}else{
				$columns = $default_cols;
			}
			if(null!=$this->input->post('download')){
				$data['users'] = $users = $this->Osi_model->getAllUsers($columns,FALSE);
			}else{
				$data['users'] = $users = $this->Osi_model->getAllUsers($columns,TRUE);
			}
			if(in_array('bat_id',$columns)){
				$columns =array_merge(array('nickname'),$columns);
			}
			//echo count($users);
			//die;
			if(null!=$this->input->post('submitForm')){
				$data['columns']=$columns;
			}elseif(null!=$this->input->post('download')){
				$this->createCSV($users, $columns);
				//$this->createAllUserExcel($users, $columns);
			}else{	//download
				$data['columns']=$columns;
			}
			if(in_array('posting',$columns)){
				$columns = array_merge(array('posting',$columns));
			}
			$this->load->view('Osi/allUsers',$data);
		}
		public function createAllUserExcel($users,$columns){
			set_time_limit(0);
			ini_set("memory_limit","-1");
			error_reporting(0);
			$this->load->library('excel');
			$objPHPExcel = new PHPExcel();
			$objPHPExcel->getProperties()->setCreator("ERMS-PAP")
										 ->setLastModifiedBy("ERMS-PAP")
										 ->setTitle("Office 2007 XLSX Test Document")
										 ->setSubject("Office 2007 XLSX Test Document")
										 ->setDescription("Vehicle consolidated figures, Generated by ERMS-PAP.")
										 ->setKeywords("Figures of vehicles/battalion in MT")
										 ->setCategory("Vehicle/Battalion figure view");
			$counti= 0;
			$objPHPExcel->createSheet($counti);
			$objPHPExcel->setActiveSheetIndex($counti);
			$objPHPExcel->getActiveSheet()->setTitle('Figure View'); 
			$counter = 0;
			$row=1;
			$titleStyle = array(
				'font'  => array(
					'size'  => 13,
					'name'  => 'Verdana',
					'fill' => array(
						'type' => PHPExcel_Style_Fill::FILL_SOLID,
						'color' => array('rgb' => 'FF00a0')
					)
				));
			
			$objPHPExcel->setActiveSheetIndex($counti)->setCellValue('A1', 'All Users');
			$objPHPExcel->getActiveSheet()->getStyle('A1')->applyFromArray($titleStyle);
			$objPHPExcel->getActiveSheet()->getStyle('A1')->getAlignment()->setHorizontal(PHPExcel_Style_Alignment::HORIZONTAL_CENTER);
			$objPHPExcel->setActiveSheetIndex($counti)->mergeCells("A1:H1");
			
			$equipmentNameStyle = array(
				'font'  => array(
					'size'  => 12,
					'name'  => 'Verdana',
					'alignment' => array(
						'horizontal' => PHPExcel_Style_Alignment::HORIZONTAL_CENTER,
					)
				));
			
			
			$cols = array('C','D','E');
			$cols_temp = array('A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z','AA','AB','AC','AD','AE','AF','AG','AH','AI','AJ','AK','AL','AM','AN','AO','AP','AQ','AR','AS','AT','AU','AV','AW','AX','AY','AZ');
			
			$row++;
			$objPHPExcel->setActiveSheetIndex($counti)->setCellValue('A'.$row, 'S. No.');
			$i=1;
			
			$objPHPExcel->setActiveSheetIndex($counti)->setCellValue('B'.$row, 'Man ID');
			$objPHPExcel->setActiveSheetIndex($counti)->setCellValue('C'.$row, 'Name');
			$objPHPExcel->setActiveSheetIndex($counti)->setCellValue('D'.$row, 'Battalion');
			$objPHPExcel->setActiveSheetIndex($counti)->setCellValue('E'.$row, 'Staff Type');
			$objPHPExcel->setActiveSheetIndex($counti)->setCellValue('F'.$row, 'Present Rank');
			$objPHPExcel->setActiveSheetIndex($counti)->setCellValue('G'.$row, 'Belt Number');
			$objPHPExcel->setActiveSheetIndex($counti)->setCellValue('H'.$row, 'Phone Number');
			$objPHPExcel->setActiveSheetIndex($counti)->setCellValue('I'.$row, 'District');
			$objPHPExcel->setActiveSheetIndex($counti)->setCellValue('J'.$row, 'Gender');
			$objPHPExcel->setActiveSheetIndex($counti)->setCellValue('K'.$row, 'Maritial Status');
			$objPHPExcel->setActiveSheetIndex($counti)->setCellValue('L'.$row, 'Caste');
			$objPHPExcel->setActiveSheetIndex($counti)->setCellValue('M'.$row, 'Category');
			$objPHPExcel->setActiveSheetIndex($counti)->setCellValue('N'.$row, 'Blood Group');
			$objPHPExcel->setActiveSheetIndex($counti)->setCellValue('O'.$row, 'Computer Literate');
			$objPHPExcel->setActiveSheetIndex($counti)->setCellValue('P'.$row, 'Date of Birth');
			$objPHPExcel->setActiveSheetIndex($counti)->setCellValue('Q'.$row, 'Date of Enlistment');
			$objPHPExcel->setActiveSheetIndex($counti)->setCellValue('R'.$row, 'Date of Retirement');
			$objPHPExcel->setActiveSheetIndex($counti)->setCellValue('S'.$row, 'Qualification');
			$objPHPExcel->setActiveSheetIndex($counti)->setCellValue('T'.$row, 'Present Posting');
			$objPHPExcel->setActiveSheetIndex($counti)->setCellValue('U'.$row, 'Date of Posting');
			$objPHPExcel->setActiveSheetIndex($counti)->setCellValue('U'.$row, 'ONO');
			$counter = 1;
			foreach($users as $k=>$user){
				$row++;
				$objPHPExcel->setActiveSheetIndex($counti)->setCellValue('A'.$row, $counter);
				$objPHPExcel->setActiveSheetIndex($counti)->setCellValue('B'.$row, $user->man_id);
				$objPHPExcel->setActiveSheetIndex($counti)->setCellValue('C'.$row, $user->name);
				$objPHPExcel->setActiveSheetIndex($counti)->setCellValue('D'.$row, $user->nickname);
				$objPHPExcel->setActiveSheetIndex($counti)->setCellValue('E'.$row, $user->presentrank);
				$objPHPExcel->setActiveSheetIndex($counti)->setCellValue('F'.$row, $user->ierank1);
				$objPHPExcel->setActiveSheetIndex($counti)->setCellValue('G'.$row, $user->depttno);
				$objPHPExcel->setActiveSheetIndex($counti)->setCellValue('H'.$row, $user->phono1);
				$objPHPExcel->setActiveSheetIndex($counti)->setCellValue('I'.$row, $user->district);
				$objPHPExcel->setActiveSheetIndex($counti)->setCellValue('J'.$row, $user->gender);
				$objPHPExcel->setActiveSheetIndex($counti)->setCellValue('K'.$row, $user->maritalstatus);
				$objPHPExcel->setActiveSheetIndex($counti)->setCellValue('L'.$row, $user->caste);
				$objPHPExcel->setActiveSheetIndex($counti)->setCellValue('M'.$row, $user->category);
				$objPHPExcel->setActiveSheetIndex($counti)->setCellValue('N'.$row, $user->bloodgroup);
				$objPHPExcel->setActiveSheetIndex($counti)->setCellValue('O'.$row, $user->comlit);
				$objPHPExcel->setActiveSheetIndex($counti)->setCellValue('P'.$row, $user->dateofbith);
				$objPHPExcel->setActiveSheetIndex($counti)->setCellValue('Q'.$row, $user->dateofinlitment);
				$objPHPExcel->setActiveSheetIndex($counti)->setCellValue('R'.$row, $user->dateofretirment);
				$objPHPExcel->setActiveSheetIndex($counti)->setCellValue('S'.$row, $user->eduqalification1);
				$objPHPExcel->setActiveSheetIndex($counti)->setCellValue('T'.$row, trim($user->posting_concat1));
				$objPHPExcel->setActiveSheetIndex($counti)->setCellValue('U'.$row, trim($user->dateofposting1).' '.trim($user->officer_name));
				$objPHPExcel->setActiveSheetIndex($counti)->setCellValue('V'.$row, trim($user->ono));
				
				/*$pos = fetchoneinfodesc('newosip',array('man_id' => $user->man_id ),'man_id');
				if($pos!=''){
					$objPHPExcel->setActiveSheetIndex($counti)->setCellValue('T'.$row, 
						$pos->fone1.$pos->vploc.$pos->vpdis.$pos->fone2.$pos->noj.$pos->jsdis.$pos->fone3.$pos->fone4.$pos->fone5.$pos->osgloc.$pos->osgdis.$pos->fone6.$pos->fone7.$pos->fone8.$pos->fone9.$pos->bsdnob.$pos->bsddis.$pos->bsdloc.$pos->fone10.$pos->fone11.$pos->fone12.$pos->lone1.$pos->perdupod.$pos->perdudis.$pos->perduorno.$pos->perduordate.$pos->lone2.$pos->dgppod.$pos->dgpdis.$pos->dgporno.$pos->dgpordate.$pos->lone3.$pos->tertdpod.$pos->tertddis.$pos->tertdorno.$pos->tertdordate.$pos->sqone1.$pos->sqone2.$pos->sqone3.$pos->sqone4.$pos->sqone5.$pos->sstgpod.$pos->sstgdis.$pos->sstgorno.$pos->sstgordate.$pos->sqone6.$pos->sqone7.$pos->sqone8.$pos->swatpod.$pos->swatdis.$pos->swatorno.$pos->swatordate.$pos->paone1.$pos->paone2.$pos->awdpmpod.$pos->awdpmorno.$pos->awdpmordate.$pos->paone3.$pos->awdpfpod.$pos->awdpforno.$pos->awdpfordate.$pos->paone4.$pos->awdpompod.$pos->awdpomorno.$pos->awdpomordate.$pos->paone5.$pos->awdpofpod.$pos->awdpoforno.$pos->awdpofordate.$pos->paone6.$pos->paone7.$pos->paone8.$pos->paone9.$pos->paone10.$pos->paone11.$pos->paone12.$pos->paone13.$pos->paone14.$pos->paone15.$pos->paone16.$pos->paone17.$pos->paone18.$pos->paone19.$pos->paone20.$pos->paone21.$pos->paone22.$pos->paone23.$pos->paone24.$pos->paone27.$pos->ssone23.$pos->dsopod.$pos->dsoorno.$pos->dsoordate.$pos->ssone24.$pos->csojalorno.$pos->csojalordate.$pos->ssone25.$pos->mispatorno.$pos->mispatordate.$pos->ssone26.$pos->othersnod.$pos->othersnodis.$pos->othersorno.$pos->othersordate.$pos->awbone1.$pos->awbone2.$pos->pssawonof.$pos->pssaworank.$pos->pssawoordate.$pos->awbone3.$pos->osihonoo.$pos->awbone4.$pos->Readerosinbo.$pos->Orderly.$pos->telopr.$pos->darrun.$pos->awbone5.$pos->bnkgdop.$pos->awbone6.$pos->bhogpog.$pos->bhogdop.$pos->awbone7.$pos->tradestot.$pos->tradestt.$pos->tradesbat.$pos->tradesdop.$pos->tradesorno.$pos->awbone8.$pos->mtsecpod.$pos->mtsecvehno.$pos->mtsecdop.$pos->mtsecorno.$pos->awbone9.$pos->quartbradop.$pos->quartbraorno.$pos->awbone10.$pos->awbone11.$pos->awbone12.$pos->awbone13.$pos->recrutnorb.$pos->recrutorno.$pos->recrutordate.$pos->bmdone1.$pos->bmdone2.$pos->leavefrom.'&nbsp;'.$pos->leaveto.$pos->bmdone3.$pos->absentfrom.$pos->absentddr.$pos->absentdate.$pos->bmdone4.$pos->usdos.$pos->usros.$pos->bmdone5.$pos->bmdone6.$pos->bmdone7.$pos->bmdone8.$pos->bmdone9.$pos->bmdone10.$pos->instone1.$pos->instone2.$pos->instone3.$pos->instone4.$pos->traning1.$pos->traning2.$pos->traning3.$pos->btarin1.$pos->btarin2.$pos->btarin3.$pos->btarin4.$pos->btarin5.$pos->btarin6.$pos->btarin7.$pos->btarin8.$pos->btarin9.$pos->btarin10.$pos->cfpop.$pos->cfppd.$pos->cfpdop.$pos->game.$pos->adminstaff);
					
						$objPHPExcel->setActiveSheetIndex($counti)->setCellValue('U'.$row, $pos->dateofposting1);
				}*/
				$counter++;
			}

			// $objWriter = new PHPExcel_Writer_Excel2007($objPHPExcel);
			//$objWriter->save(dirname(__FILE__).'/file/dalwinder.xlsx');
			//$objWriter->save('D://dalwinder.xlsx');
			//die('file created');
//			// Redirect output to a client’s web browser (Excel2007)
			header('Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
			header('Content-Disposition: attachment;filename="all_users.xls"');
			header('Cache-Control: max-age=0');
			// If you're serving to IE 9, then the following may be needed
			header('Cache-Control: max-age=1');

			// If you're serving to IE over SSL, then the following may be needed
			header ('Expires: Mon, 26 Jul 1997 05:00:00 GMT'); // Date in the past
			header ('Last-Modified: '.gmdate('D, d M Y H:i:s').' GMT'); // always modified
			header ('Cache-Control: cache, must-revalidate'); // HTTP/1.1
			header ('Pragma: public'); // HTTP/1.0

			$objWriter = PHPExcel_IOFactory::createWriter($objPHPExcel, 'Excel2007');
			$objWriter->save('php://output');
			exit;
		}
		public function createCSV($users,$columns){
			$f = fopen("tmp.csv", "w");
			$counter = 1;
			$heading = array('S. No.',' Man id',' Name','Battalion', 'Staff type','Present Rank','Belt Number','Phone Number', 'District','Gender','Maritial Status', 'Caste','Category','Blood Group','Computer Literate', 'Date Of Birth', 'Date of enlistment','Date of retirement','Qualification', 'Present Posting','Date of Posting','ONO');
			fputcsv($f,$heading);
			foreach($users as $k=>$user){
				$v = [$counter, $user->man_id, $user->empName,$user->nickname, $user->presentrank, $user->ierank1, $user->depttno, $user->phono1, $user->district, $user->gender, $user->maritalstatus, $user->caste, $user->category, $user->bloodgroup, $user->comlit, $user->dateofbith, $user->dateofinlitment, $user->dateofretirment, $user->eduqalification1, trim($user->posting_concat1).' '.trim($user->officer_name), trim($user->dateofposting1), trim($user->ono)];
				//$v = array_merge(array($counter),$v);
				fputcsv($f, $v);
				$counter++;
			}
			// Redirect output to a client’s web browser (Excel2007)
			header("Content-type: text/csv");
			header("Content-disposition: attachment; filename = user_report.csv");
			readfile('tmp.csv');
			exit;
		}
		public function initializeMTDataAllFigure($vehicles, $battalions, $types){
			$consolidatedMTData = array();
			foreach($vehicles as $vehicle_id=>$vehicle_name){
				$consolidatedMTData[$vehicle_id]['grand_total_holding'] = 0;
				$consolidatedMTData[$vehicle_id]['grand_total_on_road'] = 0;
				$consolidatedMTData[$vehicle_id]['grand_total_off_road'] = 0;
				$consolidatedMTData[$vehicle_id]['grand_total_on_off_road']=0;
				
				$consolidatedMTData[$vehicle_id]['grand_total_on_duty'] = 0;
				$consolidatedMTData[$vehicle_id]['grand_total_off_duty'] = 0;
				
				$consolidatedMTData[$vehicle_id]['grand_total_empty_on_off_road']=0;
				$consolidatedMTData[$vehicle_id]['grand_total_holding_on_off_road']=0;
				
				$consolidatedMTData[$vehicle_id]['grand_total_empty_on_off_duty']=0;
				$consolidatedMTData[$vehicle_id]['grand_total'] = 0;
				
				foreach($battalions as $bat_id=>$bat_name){
					foreach($types as $type_id=>$type_name){
						$consolidatedMTData[$vehicle_id][$bat_id][$type_id] = 0;
					}
					$consolidatedMTData[$vehicle_id][$bat_id]['holding_on_off_road'] =0;
					
				}
			}
			return $consolidatedMTData;
		}
		/**
		*	This function is used to fetch data (on road, off road, empty_on_off_road, holding, total
		*/
		public function processCalculationsAllFigure($consolidatedMTData, $battalions, $vehicles, $types){
			
			$allVehicles = $this->MTVehicle_model->getAllVehicles($battalions, $vehicles);
			//var_dump($allVehicles);
			foreach($allVehicles as $key=>$vehicle){
				
				if($vehicle->statusofvechile=='On Road'){
					if(isset($consolidatedMTData[$vehicle->catofvechicle][$vehicle->bat_id]['on_road'])){
						$consolidatedMTData[$vehicle->catofvechicle][$vehicle->bat_id]['on_road']++;
						$consolidatedMTData[$vehicle->catofvechicle]['grand_total_on_road']++;
						$consolidatedMTData[$vehicle->catofvechicle]['grand_total_on_off_road']++;
					}
					$consolidatedMTData[$vehicle->catofvechicle][$vehicle->bat_id]['holding_on_off_road']++;
					$consolidatedMTData[$vehicle->catofvechicle]['grand_total_holding_on_off_road']++;
					
				}elseif($vehicle->statusofvechile=='Off Road'){
					if(isset($consolidatedMTData[$vehicle->catofvechicle][$vehicle->bat_id]['off_road'])){
						$consolidatedMTData[$vehicle->catofvechicle][$vehicle->bat_id]['off_road']++;
						$consolidatedMTData[$vehicle->catofvechicle]['grand_total_off_road']++;
						$consolidatedMTData[$vehicle->catofvechicle]['grand_total_on_off_road']++;
					}
					$consolidatedMTData[$vehicle->catofvechicle][$vehicle->bat_id]['holding_on_off_road']++;
					$consolidatedMTData[$vehicle->catofvechicle]['grand_total_holding_on_off_road']++;
				
				}else{
					if(isset($consolidatedMTData[$vehicle->catofvechicle][$vehicle->bat_id]['empty_on_off_road'])){
						$consolidatedMTData[$vehicle->catofvechicle][$vehicle->bat_id]['empty_on_off_road']++;
						$consolidatedMTData[$vehicle->catofvechicle]['grand_total_empty_on_off_road']++;
					}
				}
				if(isset($consolidatedMTData[$vehicle->catofvechicle][$vehicle->bat_id]['holding'])){
					$consolidatedMTData[$vehicle->catofvechicle][$vehicle->bat_id]['holding']++;
					$consolidatedMTData[$vehicle->catofvechicle]['grand_total_holding'] ++;
				}
				
				if(isset($consolidatedMTData[$vehicle->catofvechicle][$vehicle->bat_id]['total'])){
					$consolidatedMTData[$vehicle->catofvechicle][$vehicle->bat_id]['total']++;
				}
				$consolidatedMTData[$vehicle->catofvechicle]['grand_total']++;
			}
			return $consolidatedMTData;
		}
		public function figure_view(){
			$data['battalions'] = $this->sortBattalions($this->getBattalions());
			$data['vehicles'] = $this->getVehicles();
			$data['types'] = $this->getDataTypes();
			$data['figureNamesToBeSkipped'] = array('grand_total_holding','grand_total_on_road','grand_total_off_road','grand_total','grand_total_empty_on_off_road','grand_total_on_duty','grand_total_off_duty','grand_total_empty_on_off_duty','grand_total_on_off_road','grand_total_holding_on_off_road');
			$pageType = $this->input->get('page');
			
			if($pageType =='ALL_FIGURES'){
				$data['subpage'] = 'all_figures.php';
				$consolidatedMTData = array();
				if(null!=$this->input->post('battalionIds')){
					$temp_battalions = $this->input->post('battalionIds');
					foreach($temp_battalions as $k=>$v){
						$battalions__[$v] = $v;
					}
					$selected_battalions = $this->sortBattalions($battalions__);
				}else{
					//$this->getBattalions();
					$selected_battalions = $data['battalions'];
				}
				if(null!=$this->input->post('namOfVehicle')){
					$temp_vehicles= $this->input->post('namOfVehicle');
					foreach($temp_vehicles as $k=>$v){
						$_vehicles[$v] = $v;
					}
					$selected_vehicles = $_vehicles;
				}else{
					$selected_vehicles = $data['vehicles'];

				}
				$consolidatedMTData = $this->initializeMTDataAllFigure($selected_vehicles,$selected_battalions, $data['types'] );
				 
				
				
				$consolidatedMTData = $this->processCalculationsAllFigure($consolidatedMTData, array_keys($selected_battalions), $selected_vehicles, $data['types']);
				//var_dump($consolidatedMTData);
				//-----------------------------------------------------------------------
				$battalions = $selected_battalions;
				//var_dump($battalions);
				$vehicles = $selected_vehicles;
				//var_dump($vehicles);
				$allVehicles = $this->MTVehicle_model->getAllVehiclesOnOffDuty(array_keys($battalions), $vehicles);
				$selectedVehicles2 = array();
				foreach($allVehicles as $k=>$vehicle){
					
					if(in_array($vehicle->reg_no,array_keys($selectedVehicles2))){
						if(empty($vehicle->date_of_duty)){
							break;
						}
						$currentVechicleDateStr = $vehicle->date_of_duty;
						$currentdtime = DateTime::createFromFormat("d/m/Y", $currentVechicleDateStr);
						if($currentdtime){
							$currenttimestamp = $currentdtime->getTimestamp();
						}else{
							$currenttimestamp =0;
						}
						$oldVechicleDateStr = $selectedVehicles2[$vehicle->reg_no]->date_of_duty;
						$olddtime = DateTime::createFromFormat("d/m/Y", $oldVechicleDateStr);
						if($olddtime){
							$oldtimestamp = $olddtime->getTimestamp();
						}else{
							$oldtimestamp = 0;
						}
						if($currenttimestamp>$oldtimestamp){
							$selectedVehicles2[$vehicle->reg_no] = $vehicle;
						}
					}else{
						$selectedVehicles2[$vehicle->reg_no] = $vehicle;
					}
				}
				foreach($selectedVehicles2 as $key=>$vehicle){
					//var_dump($vehicle);
					//die;	
					
					//echo $vehicle->place_of_duty;
					if(in_array(trim($vehicle->place_of_duty),array('MT Section'))){
						$selectedType='off_duty';
						//$consolidatedMTData[$vehicle->catofvechicle][$vehicle->bat_id]['off_duty']++;
						if(isset($consolidatedMTData[$vehicle->catofvechicle][$vehicle->bat_id]['off_duty'])){
							
						//$battalions_grand_totals['grand_total_'.$selectedType.$vehicle->bat_id]++;
							//$battalions_grand_totals['grand_total']++;
							$consolidatedMTData[$vehicle->catofvechicle][$vehicle->bat_id]['off_duty']++;
							//$consolidatedMTData[$vehicle->catofvechicle]['grand_total_off_duty']++;
						}
					}elseif(in_array(trim($vehicle->place_of_duty),array('Ceremonial duty','Election duty','General duty','Law & duty','MT Training','MT Traning (Permanent Alloted for Training Purpose...','Office duty','Officer','Other state','Sports duty','VIP Duty'))){
						$selectedType='on_duty';
						if(isset($consolidatedMTData[$vehicle->catofvechicle][$vehicle->bat_id]['on_duty'])){
							echo $vehicle->catofvechicle;
							echo $vehicle->bat_id;
							
							//$battalions_grand_totals['grand_total_'.$selectedType.$vehicle->bat_id]++;
							//$battalions_grand_totals['grand_total']++;
							$consolidatedMTData[$vehicle->catofvechicle][$vehicle->bat_id]['on_duty']++;
							//$consolidatedMTData[$vehicle->catofvechicle]['grand_total_on_duty']++;
						}
					}else{
						
						if(isset($consolidatedMTData[$vehicle->catofvechicle][$vehicle->bat_id]['empty_on_off_duty'])){
							//$battalions_grand_totals['grand_total_'.$selectedType.$vehicle->bat_id]++;
							//$battalions_grand_totals['grand_total']++;
							$consolidatedMTData[$vehicle->catofvechicle][$vehicle->bat_id]['empty_on_off_duty']++;
							$consolidatedMTData[$vehicle->catofvechicle]['grand_total_empty_on_off_duty']++;
						}
					}
				}
				//-----------------------------------------------------------------------
				if(null!=$this->input->post('skipZeroBattalions')){
					$consolidatedMTData = $this->skipZeroBattalions($consolidatedMTData,$data['figureNamesToBeSkipped']);
				}
				if(null!=$this->input->post('download')){
					$this->createdAllFigureExcel($consolidatedMTData,$selected_vehicles,$selected_battalions,$data['figureNamesToBeSkipped']);
				}
				
				$data['consolidatedMTData'] = $consolidatedMTData;
			}
			elseif($pageType =='CONSOLIDATE'){
				$data['subpage'] = 'consolidate.php';
				//get vehicles
				if(null!=$this->input->post('vehicles')){	//select vehicles
					$vehicles = $this->input->post('vehicles');		//ok
					
				}else{		//if empty select all the vehicles
					$vehicles = $data['vehicles'];
				}
				//var_dump($vehicles);
				$data['selected_vehicles'] = array();
				foreach($vehicles as $k=>$v){
					$data['selectedVehicles'][$v]=$v;
				}
				//var_dump($data['selectedVehicles']);
				
				$units = $this->getUnits();
				$data['units'] = $units;
				//get types
				if(null!=$this->input->post('dataType')){
					$type = $this->input->post('dataType');
				}else{
					$type = 'holding_on_off_road';
				}
				$data['type'] = $type;
				$data['type_name'] = $data['types'][$type];

				//initialize
				
				$raw_data = $this->initializeConsolidateDataUnitWise($data['selectedVehicles'],$units,$type);
				$consolidatedMTData = $raw_data['consolidateMTDate'];
				$data['grandTotalData']=$grandTotalData = $raw_data['grandTotalData'];
				$raw_data2 = $this->processConsolidateDataUnitWise($consolidatedMTData,$data['selectedVehicles'],$units,$type,$grandTotalData);
				$consolidatedMTData = $raw_data2['consolidatedMTData'];
				$grandTotalData = $raw_data2['grandTotalData'];
				
				if(null!=$this->input->post('skipZeroVehicles')){
					$consolidatedMTData = $this->skipZeroVehicleConsolidatedData($consolidatedMTData,$units,$data['figureNamesToBeSkipped'],$type);
				}
				if(null!=$this->input->post('downloadConsolidateFiguresOfVehicle')){
					$this->downloadConsolidateUnitWiseData($consolidatedMTData,$data['types'],$type, $vehicles,$units,$grandTotalData);
				}
				$data['consolidatedMTData'] = $consolidatedMTData;
				$data['grandTotalData'] = $grandTotalData;
			}
			elseif($pageType =='STORE_EQUIPMENTS'){
				
				//error_reporting(0);
				$data['subpage'] = 'store_equipments.php';
				$data['units'] = $this->getUnits();
				//var_dump($data['units']);
				$data['selectedUnit'] = (null!=$this->input->post('unit'))?$this->input->post('unit'):'pap';
				//echo $data['selectedUnit'];
				
				$data['selected_battalions'] = $selected_battalions = $this->getBattalionsOfUnit($data['selectedUnit']);
				//var_dump($data['selected_battalions']);
				
				$data['selectedVehicle'] = (null!=$this->input->post('vehicles'))?$this->input->post('vehicles'):array();
				
				if(empty($data['selectedVehicle'])){
					$selected_vehicles = $data['vehicles'];
				}else{
					foreach($data['selectedVehicle'] as $k=>$val){
						$selected_vehicles[$val]=$val;
					}
				}
				
				$data['selected_vehiclesToshow'] = $selected_vehicles;
				//echo $this->input->post('equipmentDataType');
				if(null!=$this->input->post('equipmentDataType')){
					if(in_array($this->input->post('equipmentDataType'),array('off_duty','on_duty','empty_on_off_duty'))){
						//get the data from database
						$selectedType = array($this->input->post('equipmentDataType')=>$data['types'][$this->input->post('equipmentDataType')]);
						$data['selectedTypeInMessage'] = $data['types'][$this->input->post('equipmentDataType')];
						$data['dataType'] = $this->input->post('equipmentDataType');
					}else{
						$selectedType = array($this->input->post('equipmentDataType')=>$data['types'][$this->input->post('equipmentDataType')]);
						$data['selectedTypeInMessage'] = $data['types'][$this->input->post('equipmentDataType')];
						$data['dataType'] = $this->input->post('equipmentDataType');
						$data['typetobeselected'] = $this->input->post('equipmentDataType');
					}
				}else{
					$selectedType = array('holding_on_off_road'=>$data['types']['holding_on_off_road']);
					
					$data['selectedTypeInMessage'] = $data['types']['holding_on_off_road'];
					$data['typetobeselected'] = 'holding_on_off_road';
					$data['dataType'] = 'holding_on_off_road';
				}
				$data['selectedType'] = $selectedType;
				//echo $data['dataType'];	
				//var_dump($selectedType);
				if(in_array($this->input->post('equipmentDataType'),array('off_duty','on_duty','empty_on_off_duty'))){
					
					$raw_data = $this->initializeMTData($selected_vehicles, $selected_battalions, $selectedType, $data['dataType']);
					$consolidatedMTData = $raw_data['consolidatedMTData'];
					$battalions_grand_totals = $raw_data['battalions_grand_totals'];
					
					$raw_data2 = $this->processCalculationsAllFigureOnOffDuty($consolidatedMTData, array_keys($selected_battalions), $selected_vehicles, $selectedType,$battalions_grand_totals,$data['dataType']);
					$consolidatedMTData = $raw_data2['consolidatedMTData'];
					$battalions_grand_totals = $raw_data2['battalions_grand_totals'];
					/* var_dump($consolidatedMTData);
					echo '</td></tr></table>'; */
				}else{
					$raw_data = $this->initializeMTData($selected_vehicles,$selected_battalions, $selectedType, $data['dataType']);
					$consolidatedMTData = $raw_data['consolidatedMTData'];
					$battalions_grand_totals = $raw_data['battalions_grand_totals'];
					
					$raw_data2 = $this->processCalculationsAllFigure2($consolidatedMTData, array_keys($selected_battalions), $selected_vehicles, $selectedType,$battalions_grand_totals, $data['dataType']);
					$consolidatedMTData = $raw_data2['consolidatedMTData'];
					$battalions_grand_totals = $raw_data2['battalions_grand_totals'];
				}
				if(null!=$this->input->post('skipZeroVechicles')){
					$consolidatedMTData = $this->skipZeroVehicles($consolidatedMTData,$data['figureNamesToBeSkipped'],$data['dataType']);
				}
				if(null!=$this->input->post('download')){
					$this->createExcelFileStoreVehicle($consolidatedMTData,$data['dataType'],$selectedType,$data['selectedUnit'],$data['units'],$selected_battalions,$battalions_grand_totals);
				}
				
				$data['consolidatedMTData'] = $consolidatedMTData;
				$data['battalions_grand_totals'] = $battalions_grand_totals;
			}else{
				$data['subpage'] = 'all_figures.php';
				$consolidatedMTData = array();
				if(null!=$this->input->post('battalionIds')){
					$temp_battalions = $this->input->post('battalionIds');
					foreach($temp_battalions as $k=>$v){
						$battalions__[$v] = $v;
					}
					$selected_battalions = $this->sortBattalions($battalions__);
				}else{
					//$this->getBattalions();
					$selected_battalions = $data['battalions'];
				}
				if(null!=$this->input->post('namOfVehicle')){
					$temp_vehicles= $this->input->post('namOfVehicle');
					foreach($temp_vehicles as $k=>$v){
						$_vehicles[$v] = $v;
					}
					$selected_vehicles = $_vehicles;
				}else{
					$selected_vehicles = $data['vehicles'];

				}
				$consolidatedMTData = $this->initializeMTDataAllFigure($selected_vehicles,$selected_battalions, $data['types'] );
				 
				
				
				$consolidatedMTData = $this->processCalculationsAllFigure($consolidatedMTData, array_keys($selected_battalions), $selected_vehicles, $data['types']);
				//var_dump($consolidatedMTData);
				if(null!=$this->input->post('skipZeroBattalions')){
					$consolidatedMTData = $this->skipZeroBattalions($consolidatedMTData,$data['figureNamesToBeSkipped']);
				}
				if(null!=$this->input->post('download')){
					$this->createdAllFigureExcel($consolidatedMTData,$selected_vehicles,$selected_battalions,$data['figureNamesToBeSkipped']);
				}
				$data['consolidatedMTData'] = $consolidatedMTData;/*
				$data['subpage'] = 'all_figures.php';
				$consolidatedMTData = array();
				if(null!=$this->input->post('battalionIds')){
					$temp_battalions = $this->input->post('battalionIds');
					foreach($temp_battalions as $k=>$v){
						$battalions__[$v] = $v;
					}
					$selected_battalions = $this->sortBattalions($battalions__);
				}else{
					//$this->getBattalions();
					$selected_battalions = $data['battalions'];
				}
				if(null!=$this->input->post('namOfVehicle')){
					$temp_vehicles= $this->input->post('namOfVehicle');
					foreach($temp_vehicles as $k=>$v){
						$_vehicles[$v] = $v;
					}
					$selected_vehicles = $_vehicles;
				}else{
					$selected_vehicles = $data['vehicles'];

				}
				$consolidatedMTData = $this->initializeMTData($selected_vehicles,$selected_battalions, $data['types']);
				$consolidatedMTData = $this->processCalculationsAllFigure($consolidatedMTData, array_keys($selected_battalions), $selected_vehicles, $data['types']);
				$data['consolidatedMTData'] = $consolidatedMTData;*/
			}
			$this->load->view('MTVehicles/figure_view.php',$data);
		}
		public function skipZeroVehicleConsolidatedData($data,$units,$figureNamesToBeSkipped,$type){
			
			$processedData = array();
			foreach($data as $vehicleid=>$battalion){
				$keep = false;;
				foreach($battalion as $bat_id=>$parameters){
					if(!in_array($bat_id,$figureNamesToBeSkipped)){
						if(($parameters[$type]>0))
						{
							$keep = true;
							break;
						}
					}
				}
				if($keep==true){
					$processedData[$vehicleid] = $battalion;
					$processedData[$vehicleid]['grand_total_holding']= $data[$vehicleid]['grand_total_holding'];
					$processedData[$vehicleid]['grand_total_on_road']= $data[$vehicleid]['grand_total_on_road'];
					$processedData[$vehicleid]['grand_total_off_road']= $data[$vehicleid]['grand_total_off_road'];
					$processedData[$vehicleid]['grand_total_on_duty']= $data[$vehicleid]['grand_total_on_duty'];
					$processedData[$vehicleid]['grand_total_off_duty']= $data[$vehicleid]['grand_total_off_duty'];
				}
			}
			return $processedData;
			
		}
		public function skipZeroVehicles($data,$figureNamesToBeSkipped,$type){
			$processedData = array();
			foreach($data as $vehicleid=>$battalion){
				$keep = false;;
				foreach($battalion as $bat_id=>$parameters){
					if(!in_array($bat_id,$figureNamesToBeSkipped)){
						if(($parameters[$type]>0))
						{
							$keep = true;
							break;
						}
					}
				}
				if($keep==true){
					$processedData[$vehicleid] = $battalion;
					$processedData[$vehicleid]['grand_total_holding']= $data[$vehicleid]['grand_total_holding'];
					$processedData[$vehicleid]['grand_total_on_road']= $data[$vehicleid]['grand_total_on_road'];
					$processedData[$vehicleid]['grand_total_off_road']= $data[$vehicleid]['grand_total_off_road'];
					$processedData[$vehicleid]['grand_total_on_duty']= $data[$vehicleid]['grand_total_on_duty'];
					$processedData[$vehicleid]['grand_total_off_duty']= $data[$vehicleid]['grand_total_off_duty'];
				}
			}
			return $processedData;
		}
		/**
		*	initializing consolidated Data unit wise
		*/
		public function initializeConsolidateDataUnitWise($selected_vehicles,$units,$type){
			$consolidate = array();
			//$data['grand_total'] = 0;
			foreach($units as $k=>$unit_name){
				$grandTotalData['grandTotal'][$k]=0;
			}
			$grandTotalData['totalGrand'] = 0;
			foreach($selected_vehicles as $key=>$vehicle_name){
				foreach($units as $k=>$unit_name){
					$data[$vehicle_name][$k][$type] = 0;
				}
				//$data[$vehicle_name]['other']=0;
				$data[$vehicle_name]['total']=0	;
				$data[$vehicle_name]['grand_total_holding']=0	;
				$data[$vehicle_name]['grand_total_'.$type]=0;
				$data[$vehicle_name]['grand_total_holding'] = 0;
				$data[$vehicle_name]['grand_total_on_road'] = 0;
				$data[$vehicle_name]['grand_total_off_road'] = 0;
				$data[$vehicle_name]['grand_total_on_off_road']=0;
				
				$data[$vehicle_name]['grand_total_on_duty'] = 0;
				$data[$vehicle_name]['grand_total_off_duty'] = 0;
				
				$data[$vehicle_name]['grand_total_empty_on_off_road']=0;
				$data[$vehicle_name]['grand_total_holding_on_off_road']=0;
				
				$data[$vehicle_name]['grand_total_empty_on_off_duty']=0;
				$data[$vehicle_name]['grand_total'] = 0;
				
			}
			return array('consolidateMTDate'=>$data,'grandTotalData'=>$grandTotalData);
		}
		public function processConsolidateDataUnitWise($consolidatedMTData,$vehicles,$units,$type,$grandTotalData){
			
			
			$battalions = $this->getBattalions();
		
			if(in_array($type, array('on_road','off_road','holding_on_off_road','empty_on_off_road'))){
				$allVehicles = $this->MTVehicle_model->getAllVehicles(array_keys($battalions), $vehicles);
				foreach($allVehicles as $key=>$vehicle){
					
					$bat_id = $vehicle->bat_id;
					//var_dump($vehicle);
					//die;
					if($type=='on_road' && $vehicle->statusofvechile=='On Road'){
						$unit = $this->getUnitByBattalionId($bat_id);
						$consolidatedMTData[$vehicle->catofvechicle][$unit][$type]++;
						$consolidatedMTData[$vehicle->catofvechicle]['grand_total_holding']++;
						$consolidatedMTData[$vehicle->catofvechicle]['grand_total_'.$type]++;
						$grandTotalData['grandTotal'][$unit]++;
						$grandTotalData['totalGrand']++;
					}elseif($type=='off_road' && $vehicle->statusofvechile=='Off Road'){
						$unit = $this->getUnitByBattalionId($bat_id);
						$consolidatedMTData[$vehicle->catofvechicle][$unit][$type]++;
						$consolidatedMTData[$vehicle->catofvechicle]['grand_total_holding']++;
						$consolidatedMTData[$vehicle->catofvechicle]['grand_total_'.$type]++;
						$grandTotalData['grandTotal'][$unit]++;
						$grandTotalData['totalGrand']++;
					}elseif($type=='holding_on_off_road' && in_array($vehicle->statusofvechile,array('On Road','Off Road'))){
						$unit = $this->getUnitByBattalionId($bat_id);
						$consolidatedMTData[$vehicle->catofvechicle][$unit][$type]++;
						$consolidatedMTData[$vehicle->catofvechicle]['grand_total_holding']++;
						$consolidatedMTData[$vehicle->catofvechicle]['grand_total_'.$type]++;
						$grandTotalData['grandTotal'][$unit]++;
						$grandTotalData['totalGrand']++;
					}elseif(($type=='empty_on_off_road') && !in_array($vehicle->statusofvechile,array('On Road','Off Road'))){
						
						$unit = $this->getUnitByBattalionId($bat_id);
						$consolidatedMTData[$vehicle->catofvechicle][$unit][$type]++;
						$consolidatedMTData[$vehicle->catofvechicle]['grand_total_holding']++;
						$consolidatedMTData[$vehicle->catofvechicle]['grand_total_'.$type]++;
						$grandTotalData['grandTotal'][$unit]++;
						$grandTotalData['totalGrand']++;
					}
				}
			
			}
			elseif(in_array($type,array('on_duty','off_duty','empty_on_off_duty'))){
				
				$allVehicles = $this->MTVehicle_model->getAllVehiclesOnOffDuty(array_keys($battalions), $vehicles);
				//echo '<hr>';
				//var_dump($allVehicles);
				//if(false){
				$selectedVehicles = array();
				foreach($allVehicles as $k=>$vehicle){
					if(in_array($vehicle->reg_no,array_keys($selectedVehicles))){
						if(empty($vehicle->date_of_duty)){
							break;
						}
						$currentVechicleDateStr = $vehicle->date_of_duty;
						$currentdtime = DateTime::createFromFormat("d/m/Y", $currentVechicleDateStr);
						if($currentdtime){
							$currenttimestamp = $currentdtime->getTimestamp();
						}else{
							$currenttimestamp =0;
						}
						$oldVechicleDateStr = $selectedVehicles[$vehicle->reg_no]->date_of_duty;
						$olddtime = DateTime::createFromFormat("d/m/Y", $oldVechicleDateStr);
						if($olddtime){
							$oldtimestamp = $olddtime->getTimestamp();
						}else{
							$oldtimestamp = 0;
						}
						if($currenttimestamp>$oldtimestamp){
							$selectedVehicles[$vehicle->reg_no] = $vehicle;
						}
					}else{
						$selectedVehicles[$vehicle->reg_no] = $vehicle;
					}
				}
				//echo '<pre>';
				//var_dump($selectedVehicles);
				
				foreach($selectedVehicles as $key=>$vehicle){
					//var_dump($vehicle);
					$unit = $this->getUnitByBattalionId($vehicle->bat_id);
					
					if(in_array($vehicle->place_of_duty,array('MT Section'))){
						if(isset($consolidatedMTData[$vehicle->catofvechicle][$unit]['off_duty'])){
							$consolidatedMTData[$vehicle->catofvechicle][$unit]['off_duty']++;
							$consolidatedMTData[$vehicle->catofvechicle]['grand_total_off_duty']++;
							$grandTotalData['grandTotal'][$unit]++;
							$grandTotalData['totalGrand']++;
						}
					}elseif(in_array(trim($vehicle->place_of_duty),array('Ceremonial duty','Election duty','General duty','Law & duty','MT Training','MT Traning (Permanent Alloted for Training Purpose...','Office duty','Officer','Other state','Sports duty','VIP Duty'))){
						if(isset($consolidatedMTData[$vehicle->catofvechicle][$unit]['on_duty'])){
							$consolidatedMTData[$vehicle->catofvechicle][$unit]['on_duty']++;
							$consolidatedMTData[$vehicle->catofvechicle]['grand_total_on_duty']++;
							$grandTotalData['grandTotal'][$unit]++;
							$grandTotalData['totalGrand']++;
						}
					}else{
						if(isset($consolidatedMTData[$vehicle->catofvechicle][$unit]['empty_on_off_duty'])){
							$consolidatedMTData[$vehicle->catofvechicle][$unit]['empty_on_off_duty']++;
							$consolidatedMTData[$vehicle->catofvechicle]['grand_total_empty_on_off_duty']++;
							$grandTotalData['grandTotal'][$unit]++;
							$grandTotalData['totalGrand']++;
						}
					}
					
				}
			}//}
			return array('consolidatedMTData'=>$consolidatedMTData, 'grandTotalData'=>$grandTotalData);
		}
		public function skipZeroBattalions($data,$figureNamesToBeSkipped){
			
			$processedData = array();
			foreach($data as $vehicleid=>$battalion){
				foreach($battalion as $bat_id=>$parameters){ 
					if(!in_array($bat_id,$figureNamesToBeSkipped)){
						if(!(($parameters['on_road']==0) && ($parameters['off_road']==0) && ($parameters['holding_on_off_road']==0)))
						{	
							$processedData[$vehicleid][$bat_id]=$parameters;
						}else{
							
						}
					}
				}
				
				$processedData[$vehicleid]['grand_total_on_off_road']= $data[$vehicleid]['grand_total_on_off_road'];
				$processedData[$vehicleid]['grand_total_holding']= $data[$vehicleid]['grand_total_holding'];
				$processedData[$vehicleid]['grand_total_on_road']= $data[$vehicleid]['grand_total_on_road'];
				$processedData[$vehicleid]['grand_total_off_road']= $data[$vehicleid]['grand_total_off_road'];
				$processedData[$vehicleid]['grand_total_on_duty']= $data[$vehicleid]['grand_total_on_duty'];
				$processedData[$vehicleid]['grand_total_off_duty']= $data[$vehicleid]['grand_total_off_duty'];
			}
			//var_dump($processedData);
			if(null!=$this->input->post('skipZeroVehicle')){
				foreach($processedData as $vehicleid=>$battalion){
					if((count($battalion)-VARIABLE_QUANTITY)==0){
						unset($processedData[$vehicleid]);
					}
				}
			}
			return $processedData;
		}
		/**
		*	This function is used to fetch data (on road, off road, empty_on_off_road, holding, total
		*/
		public function processCalculationsAllFigure2($consolidatedMTData, $battalions, $vehicles, $types,$battalions_grand_totals,$selectedType){
			
			$allVehicles = $this->MTVehicle_model->getAllVehicles($battalions, $vehicles);
			//var_dump($allVehicles);
			foreach($allVehicles as $key=>$vehicle){
				if($selectedType=='on_road'){
					if($vehicle->statusofvechile=='On Road'){
						if(isset($consolidatedMTData[$vehicle->catofvechicle][$vehicle->bat_id]['on_road'])){
							$battalions_grand_totals['grand_total_'.$selectedType.$vehicle->bat_id]++;
							$battalions_grand_totals['grand_total']++;
							$consolidatedMTData[$vehicle->catofvechicle][$vehicle->bat_id]['on_road']++;
							$consolidatedMTData[$vehicle->catofvechicle]['grand_total_on_road']++;
							$consolidatedMTData[$vehicle->catofvechicle]['grand_total_on_off_road']++;
						}
					}
				}elseif($selectedType=="off_road"){
					if($vehicle->statusofvechile=='Off Road'){
						if(isset($consolidatedMTData[$vehicle->catofvechicle][$vehicle->bat_id]['off_road'])){
							$battalions_grand_totals['grand_total_'.$selectedType.$vehicle->bat_id]++;
							$battalions_grand_totals['grand_total']++;
							$consolidatedMTData[$vehicle->catofvechicle][$vehicle->bat_id]['off_road']++;
							$consolidatedMTData[$vehicle->catofvechicle]['grand_total_off_road']++;
							$consolidatedMTData[$vehicle->catofvechicle]['grand_total_on_off_road']++;
						}
					}
				}elseif($selectedType=='holding_on_off_road'){
					
					if(in_array($vehicle->statusofvechile,array('On Road','Off Road'))){
						
						if(isset($consolidatedMTData[$vehicle->catofvechicle][$vehicle->bat_id]['holding_on_off_road'])){
							$battalions_grand_totals['grand_total_'.$selectedType.$vehicle->bat_id]++;
							$battalions_grand_totals['grand_total']++;
							$consolidatedMTData[$vehicle->catofvechicle][$vehicle->bat_id]['holding_on_off_road']++;
							$consolidatedMTData[$vehicle->catofvechicle]['grand_total_holding_on_off_road']++;
						}
					}
				}elseif($selectedType=='empty_on_off_road'){
					
					if(!in_array($vehicle->statusofvechile,array('On Road','Off Road'))){
						echo 'hi';
						if(isset($consolidatedMTData[$vehicle->catofvechicle][$vehicle->bat_id]['empty_on_off_road'])){
							$battalions_grand_totals['grand_total_'.$selectedType.$vehicle->bat_id]++;
							$battalions_grand_totals['grand_total']++;
							$consolidatedMTData[$vehicle->catofvechicle][$vehicle->bat_id]['empty_on_off_road']++;
							$consolidatedMTData[$vehicle->catofvechicle]['grand_total_empty_on_off_road']++;
						}
					}
				}else{
					die('Invalid Type Selected!!');
				}
			}
			return array('consolidatedMTData'=>$consolidatedMTData,'battalions_grand_totals'=>$battalions_grand_totals);
		}
		
		
		public function initializeMTData($vehicles, $battalions, $types, $selectedType='holding_on_off_road'){
			$consolidatedMTData = array();
			$battalions_grand_totals = array();
			foreach($battalions as $bat_id=>$bat_name){
				$battalions_grand_totals['grand_total_'.$selectedType.$bat_id] = 0;
			}
			$battalions_grand_totals['grand_total'] = 0;
			foreach($vehicles as $vehicle_id=>$vehicle_name){
				$consolidatedMTData[$vehicle_id]['grand_total_holding'] = 0;
				$consolidatedMTData[$vehicle_id]['grand_total_on_road'] = 0;
				$consolidatedMTData[$vehicle_id]['grand_total_off_road'] = 0;
				$consolidatedMTData[$vehicle_id]['grand_total_on_off_road']=0;
				
				$consolidatedMTData[$vehicle_id]['grand_total_on_duty'] = 0;
				$consolidatedMTData[$vehicle_id]['grand_total_off_duty'] = 0;
				
				$consolidatedMTData[$vehicle_id]['grand_total_empty_on_off_road']=0;
				$consolidatedMTData[$vehicle_id]['grand_total_holding_on_off_road']=0;
				
				$consolidatedMTData[$vehicle_id]['grand_total_empty_on_off_duty']=0;
				$consolidatedMTData[$vehicle_id]['grand_total'] = 0;
				
				foreach($battalions as $bat_id=>$bat_name){
					foreach($types as $type_id=>$type_name){
						$consolidatedMTData[$vehicle_id][$bat_id][$type_id] = 0;
					}
					$consolidatedMTData[$vehicle_id][$bat_id]['holding_on_off_road'] =0;
					
				}
			}
			return array('consolidatedMTData'=>$consolidatedMTData,'battalions_grand_totals'=>$battalions_grand_totals);
		}
		/**
		*	This function is used to fetch data (on dury, off duty figures
		*/
		public function processCalculationsAllFigureOnOffDuty($consolidatedMTData, $battalions, $vehicles, $types,$battalions_grand_totals,$selectedType){
			//var_dump($battalions);
			
			$allVehicles = $this->MTVehicle_model->getAllVehiclesOnOffDuty($battalions, $vehicles);
				
			//if(false){
			$selectedVehicles = array();
			foreach($allVehicles as $k=>$vehicle){
				
				if(in_array($vehicle->reg_no,array_keys($selectedVehicles))){
					if(empty($vehicle->date_of_duty)){
						break;
					}
					$currentVechicleDateStr = $vehicle->date_of_duty;
					$currentdtime = DateTime::createFromFormat("d/m/Y", $currentVechicleDateStr);
					if($currentdtime){
						$currenttimestamp = $currentdtime->getTimestamp();
					}else{
						$currenttimestamp =0;
					}
					$oldVechicleDateStr = $selectedVehicles[$vehicle->reg_no]->date_of_duty;
					$olddtime = DateTime::createFromFormat("d/m/Y", $oldVechicleDateStr);
					if($olddtime){
						$oldtimestamp = $olddtime->getTimestamp();
					}else{
						$oldtimestamp = 0;
					}
					if($currenttimestamp>$oldtimestamp){
						$selectedVehicles[$vehicle->reg_no] = $vehicle;
					}
				}else{
					$selectedVehicles[$vehicle->reg_no] = $vehicle;
				}
			}
			foreach($selectedVehicles as $key=>$vehicle){
				//var_dump($vehicle);
				//die;	
				if(in_array(trim($vehicle->place_of_duty),array('MT Section'))){
					
					if(isset($consolidatedMTData[$vehicle->catofvechicle][$vehicle->bat_id]['off_duty'])){
						$battalions_grand_totals['grand_total_'.$selectedType.$vehicle->bat_id]++;
						$battalions_grand_totals['grand_total']++;
						$consolidatedMTData[$vehicle->catofvechicle][$vehicle->bat_id]['off_duty']++;
						$consolidatedMTData[$vehicle->catofvechicle]['grand_total_off_duty']++;
					}
				}elseif(in_array(trim($vehicle->place_of_duty),array('Ceremonial duty','Election duty','General duty','Law & duty','MT Training','MT Traning (Permanent Alloted for Training Purpose...','Office duty','Officer','Other state','Sports duty','VIP Duty'))){
					
					if(isset($consolidatedMTData[$vehicle->catofvechicle][$vehicle->bat_id]['on_duty'])){
						
						$battalions_grand_totals['grand_total_'.$selectedType.$vehicle->bat_id]++;
						$battalions_grand_totals['grand_total']++;
						$consolidatedMTData[$vehicle->catofvechicle][$vehicle->bat_id]['on_duty']++;
						$consolidatedMTData[$vehicle->catofvechicle]['grand_total_on_duty']++;
					}
				}else{
					
					if(isset($consolidatedMTData[$vehicle->catofvechicle][$vehicle->bat_id]['empty_on_off_duty'])){
						$battalions_grand_totals['grand_total_'.$selectedType.$vehicle->bat_id]++;
						$battalions_grand_totals['grand_total']++;
						$consolidatedMTData[$vehicle->catofvechicle][$vehicle->bat_id]['empty_on_off_duty']++;
						$consolidatedMTData[$vehicle->catofvechicle]['grand_total_empty_on_off_duty']++;
					}
				}
			}
			//} 
			return array('consolidatedMTData'=>$consolidatedMTData,'battalions_grand_totals'=>$battalions_grand_totals);
		}
		/**
		*	This function will return all the vehicles
		*/
		public function getVehicles(){
			return  array('Ambulance' => 'Ambulance', 'BUS 52 Seater' => 'BUS 52 Seater', 'Truck' => 'Truck', 'Canter/Tata 407' => 'Canter/Tata 407', 'M/Cycle (Royel Enfield)' => 'M/Cycle (Royel Enfield)', 'M/Cycle (Bajaj Pulsar)' => 'M/Cycle (Bajaj Pulsar)', 'Mini Bus' => 'Mini Bus','Toyota (Kirloskar Motor)' => 'Toyota (Kirloskar Motor)','Bolero (M & M)' => 'Bolero (M & M)', 'Xylo (M & M)' => 'Xylo (M & M)', 'Maruti Suzuki (Ertiga)' =>'Maruti Suzuki (Ertiga)', 'Scorpio (M & M)' => 'Scorpio (M & M)', 'Tata Sumo' => 'Tata Sumo','Gypsy' =>'Gypsy','Sumo Victa' => 'Sumo Victa','Jeep' => 'Jeep', 'Water Tank' => 'Water Tank','Tractor' => 'Tractor','Ambassador Car' => 'Ambassador Car','M/Cycle (Suzuki)' => 'M/Cycle (Suzuki)','Van (Maruti Omni)' => 'Van (Maruti Omni)','Canter (Eicher)' => 'Canter (Eicher)','Bus 42 Seater' => 'Bus 42 Seater','Mahindra Invader' => 'Mahindra Invader', 'Bus 44 Seater' => 'Bus 44 Seater','Bus 45 Seater' => 'Bus 45 Seater','M/Cycle (Hero Karizma)' => 'M/Cycle (Hero Karizma)','Qualis' => 'Qualis','Tempo Trax Gama' => 'Tempo Trax Gama','Hero Honda' => 'Hero Honda','Bajaj Platina' => 'Bajaj Platina','Innova' => 'Innova','Maruti Suzuki SX-4' => 'Maruti Suzuki SX-4','Truck (Training)' => 'Truck (Training)','Gypsy (Training)' =>'Gypsy (Training)','Canter/Tata 407 (Training)' => 'Canter/Tata 407 (Training)','M/Cycle (Suzuki)(Training)' => 'M/Cycle (Suzuki) (Training)','Bolero (M & M) (Training)' => 'Bolero (M & M) (Training)','Mini Bus (Training)' => 'Mini Bus (Training)','Ambassador Car (Training)' => 'Ambassador Car (Training)','M/Cycle (Royel Enfield) (Training)' => 'M/Cycle (Royel Enfield) (Training)','MAP Truck'=>'MAP 	Truck');
		}
		/**
		*	This function will return the vehicle types
		*/
		public function getVehicleType(){
			return  array('' => '--Select--', 'Vajara' => 'Vajara','Water cannon' => 'Water cannon', 'Ambulance' => 'Ambulance', 'recovery Van' => 'recovery Van' ,'General duty' => 'General duty','MT Training Duty' => 'MT Training Duty');
		}
		/**
		*	Fetch all those battalions/units which have mt section
		*/
		public function getBattalions(){
			$data =  $this->MTVehicle_model->getBattalions();
			$battalions = array();
			foreach($data as $k=>$bat){
				$battalions[$bat->users_id] = $bat->user_name;
			}
			return $battalions;
		}
		/***
		* This function is used to sort the battalion
		* @input: battalion array with id=>name pair
		*/
		public function sortBattalions($battalions){
			$battalionOrder = array(
					34=>'7 - PAP',
					106=>'9 - PAP',
					135=>'13 - PAP',
					48=>'27 - PAP',
					188=>'36 - PAP',
					9=>'75 - PAP',
					55=>'80 - PAP',
					140=>'82 - PAP',
					76=>'RTC - PAP',
					130=>'ISTC',
				//68=>'CSO PAP',
				//61=>'ADGP PAP',
					194=>'1 - IRB',
					170=>'2 - IRB',
					158=>'3 - IRB',
					116=>'4 - IRB',
					111=>'5 - IRB',
					169=>'6 - IRB',
					124=>'7 - IRB',
				//214=>'IGP - IRB',
					206=>'RTC LADDA KOTHI - IRB',
					208=>'1 - CDO',
					176=>'2 - CDO',
					146=>'3 - CDO',
					152=>'4 - CDO',
					182=>'5 - CDO',
				//215=>'IGP - CDO',
					200=>'CTC - BG'
			);
			$sortedBattalions = array();
			foreach($battalionOrder as $id=>$name){
				if(isset($battalions[$id])){
					$sortedBattalions[$id] = $name;
				}
			}
			return $sortedBattalions;
		}
		public function getDataTypes(){
			return array('on_road'=>'On Road','off_road'=>'OFF ROAD','holding_on_off_road'=>'Total of ON/OFF Road','empty_on_off_road'=>'Empty on/off Road','on_duty'=>'On Duty','off_duty'=>'Available in MT',/*'total'=>'Total',*/'empty_on_off_duty'=>'Empty ON/OFF Duty');
		}
		/**
		*	it will return all the units in punjab armed police
		*/
		public function getUnits(){
			return array('pap'=>'PAP', 'irb'=>'IRB', 'cdo'=>'CDO', 'other'=>'Other');
		}
		public function getBattalionsOfUnit($unit){
			if($unit=='pap'){
				$battalions = array(
					34=>'7 - PAP',
					106=>'9 - PAP',
					135=>'13 - PAP',
					48=>'27 - PAP',
					188=>'36 - PAP',
					9=>'75 - PAP',
					55=>'80 - PAP',
					140=>'82 - PAP',
					76=>'RTC - PAP',
					130=>'ISTC'
					//68=>'CSO PAP',
					//61=>'ADGP PAP',
				);
			}elseif($unit=='irb'){
				
				$battalions = array(
					194=>'1 - IRB',
					170=>'2 - IRB',
					158=>'3 - IRB',
					116=>'4 - IRB',
					111=>'5 - IRB',
					169=>'6 - IRB',
					124=>'7 - IRB',
				//214=>'IGP - IRB',
					206=>'RTC LADDA KOTHI - IRB'
				);
			}elseif($unit=='cdo'){
				$battalions=array(
					208=>'1 - CDO',
					176=>'2 - CDO',
					146=>'3 - CDO',
					152=>'4 - CDO',
					182=>'5 - CDO',
				//215=>'IGP - CDO',
					200=>'CTC - BG'
				);
			}
			return $battalions;
		}
		/**
		*	This function will fettche the unit by passsing bat id  as input
		*/
		public function getUnitByBattalionId($bat_id){
			if(in_array($bat_id,array(34,106,135,48,188,9,55,140,76,130))){
				return 'pap';
			}elseif(in_array($bat_id,array(194,170,158,116,111,169,124,206))){
				return 'irb';
			}elseif(in_array($bat_id,array(208,176,146,152,182,200))){
				return 'cdo';
			}else{
				return 'other';
			}
		}
		/**
		*	Genrating excel sheet for all figures
		*/
		public function createdAllFigureExcel($data,$vehicles,$battalions,$figureNamesToBeSkipped){
			$this->load->library('excel');
			$objPHPExcel = new PHPExcel();
			$objPHPExcel->getProperties()->setCreator("ERMS-PAP")
										 ->setLastModifiedBy("ERMS-PAP")
										 ->setTitle("Office 2007 XLSX Test Document")
										 ->setSubject("Office 2007 XLSX Test Document")
										 ->setDescription("Vehicle consolidated figures, Generated by ERMS-PAP.")
										 ->setKeywords("Figures of vehicles in MT")
										 ->setCategory("Equipment figure view");
			$counti= 0;
			$objPHPExcel->createSheet($counti);
			$objPHPExcel->setActiveSheetIndex($counti);
			$objPHPExcel->getActiveSheet()->setTitle('Figure View'); 
			$counter = 0;
			$row=1;
			$titleStyle = array(
				'font'  => array(
					'size'  => 15,
					'name'  => 'Verdana',
					'fill' => array(
						'type' => PHPExcel_Style_Fill::FILL_SOLID,
						'color' => array('rgb' => 'FF00a0')
					)
				));
			
			$objPHPExcel->setActiveSheetIndex($counti)->setCellValue('A1', 'Figures of vehicles in respective Battalions');
			$objPHPExcel->getActiveSheet()->getStyle('A1')->applyFromArray($titleStyle);
			$objPHPExcel->getActiveSheet()->getStyle('A1')->getAlignment()->setHorizontal(PHPExcel_Style_Alignment::HORIZONTAL_CENTER);
			$objPHPExcel->setActiveSheetIndex($counti)->mergeCells("A1:E1");
			$row++;
			$equipmentNameStyle = array(
				'font'  => array(
					'size'  => 12,
					'name'  => 'Verdana',
					'alignment' => array(
						'horizontal' => PHPExcel_Style_Alignment::HORIZONTAL_CENTER,
					)
				));
			
			
			$cols = array('C','D','E');
			$cols_temp = array('A','B','C','D','E');
			$i=0;
			
			$row++;
			$objPHPExcel->getActiveSheet()->getColumnDimension('B')->setWidth(25);
			$counter = 1;
			$objPHPExcel->getActiveSheet()
    ->getStyle('A')
    ->getAlignment()
    ->setHorizontal(PHPExcel_Style_Alignment::HORIZONTAL_LEFT);
			foreach($data as $vehicleid=>$battalion){
				$objPHPExcel->setActiveSheetIndex($counti)->setCellValue('A'.$row, $vehicles[$vehicleid]); //name of vechicel
				$objPHPExcel->getActiveSheet()->getStyle('A'.$row)->getFont()->setBold(true);
				$objPHPExcel->setActiveSheetIndex($counti)->mergeCells("A".$row.":E".$row);
				$objPHPExcel->getActiveSheet()->getStyle('A'.$row)->getAlignment()->setHorizontal(PHPExcel_Style_Alignment::HORIZONTAL_CENTER);
				$objPHPExcel->getActiveSheet()->getStyle('A'.$row)->applyFromArray(
					array(
						'fill' => array(
							'type' => PHPExcel_Style_Fill::FILL_SOLID,
							'color' => array('rgb' => 'c0c0c0')
						)
					)
				);
				//table col name
				$row++;
				$objPHPExcel->setActiveSheetIndex($counti)->setCellValue('A'.$row, 'S. No.');
				$objPHPExcel->setActiveSheetIndex($counti)->setCellValue('B'.$row, 'Battalion');
				$objPHPExcel->setActiveSheetIndex($counti)->setCellValue('C'.$row, 'Holding');
				$objPHPExcel->setActiveSheetIndex($counti)->setCellValue('D'.$row, 'On Road');
				$objPHPExcel->setActiveSheetIndex($counti)->setCellValue('E'.$row, 'Off Road');
				
				
				foreach($cols_temp as $k=>$v){
					$objPHPExcel->getActiveSheet()->getStyle($v.$row)->applyFromArray(
						array(
							'fill' => array(
								'type' => PHPExcel_Style_Fill::FILL_SOLID,
								'color' => array('rgb' => 'F3F5F7')
							)
						)
					);
					$objPHPExcel->getActiveSheet()->getStyle($v.$row)->getFont()->setBold(true);
				}
				//echo '<tr><td>'.$v2.'</td>';
				$i=0;
				if(count($battalion)>VARIABLE_QUANTITY){
					foreach($battalion as $bat_id=>$parameters){ 
						if(!in_array($bat_id,$figureNamesToBeSkipped)){
							$i++;
							$row++;
							$objPHPExcel->setActiveSheetIndex($counti)->setCellValue('A'.$row, $i);
							$objPHPExcel->setActiveSheetIndex($counti)->setCellValue('B'.$row, $battalions[$bat_id]);
							$objPHPExcel->setActiveSheetIndex($counti)->setCellValue('C'.$row, $parameters['holding_on_off_road']);
							$objPHPExcel->setActiveSheetIndex($counti)->setCellValue('D'.$row, $parameters['on_road']);
							$objPHPExcel->setActiveSheetIndex($counti)->setCellValue('E'.$row, $parameters['off_road']);
						}
					}
					
				}else{
					$row++;
					$objPHPExcel->setActiveSheetIndex($counti)->setCellValue('A'.$row, 'No Data Found!!');
					$objPHPExcel->setActiveSheetIndex($counti)->mergeCells("A".$row.":E".$row);
					$objPHPExcel->getActiveSheet()->getStyle('A'.$row)->getAlignment()->setHorizontal(PHPExcel_Style_Alignment::HORIZONTAL_CENTER);
				}
				$row++;	
				$objPHPExcel->setActiveSheetIndex($counti)->setCellValue('B'.$row, 'Grand Total');
				$objPHPExcel->setActiveSheetIndex($counti)->setCellValue('C'.$row, $battalion['grand_total_on_off_road']);
				$objPHPExcel->setActiveSheetIndex($counti)->setCellValue('D'.$row, $battalion['grand_total_on_road']);
				$objPHPExcel->setActiveSheetIndex($counti)->setCellValue('E'.$row, $battalion['grand_total_off_road']);
				
				foreach($cols_temp as $k=>$v){
					$objPHPExcel->getActiveSheet()->getStyle($v.$row)->applyFromArray(
						array(
							'fill' => array(
								'type' => PHPExcel_Style_Fill::FILL_SOLID,
								'color' => array('rgb' => 'F3F5F7')
							)
						)
					);
					$objPHPExcel->getActiveSheet()->getStyle($v.$row)->getFont()->setBold(true);
				}
				
				$row++;
				$row++;
			}
			
			//die;
//			// Redirect output to a client’s web browser (Excel2007)
			header('Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
			header('Content-Disposition: attachment;filename="all_vehicle_figures.xlsx"');
			header('Cache-Control: max-age=0');
			// If you're serving to IE 9, then the following may be needed
			header('Cache-Control: max-age=1');

			// If you're serving to IE over SSL, then the following may be needed
			header ('Expires: Mon, 26 Jul 1997 05:00:00 GMT'); // Date in the past
			header ('Last-Modified: '.gmdate('D, d M Y H:i:s').' GMT'); // always modified
			header ('Cache-Control: cache, must-revalidate'); // HTTP/1.1
			header ('Pragma: public'); // HTTP/1.0

			$objWriter = PHPExcel_IOFactory::createWriter($objPHPExcel, 'Excel2007');
			$objWriter->save('php://output');
			exit;
		}
		/**
		*	Genrating excel sheet for vehicles
		*/
		public function createExcelFileStoreVehicle($data,$selectedType,$types,$selectedUnit,$units,$selected_battalions,$battalionGrandTotals){
			$this->load->library('excel');
			$objPHPExcel = new PHPExcel();
			$objPHPExcel->getProperties()->setCreator("ERMS-PAP")
										 ->setLastModifiedBy("ERMS-PAP")
										 ->setTitle("Office 2007 XLSX Test Document")
										 ->setSubject("Office 2007 XLSX Test Document")
										 ->setDescription("Vehicle consolidated figures, Generated by ERMS-PAP.")
										 ->setKeywords("Figures of vehicles/battalion in MT")
										 ->setCategory("Vehicle/Battalion figure view");
			$counti= 0;
			$objPHPExcel->createSheet($counti);
			$objPHPExcel->setActiveSheetIndex($counti);
			$objPHPExcel->getActiveSheet()->setTitle('Figure View'); 
			$counter = 0;
			$row=1;
			$titleStyle = array(
				'font'  => array(
					'size'  => 15,
					'name'  => 'Verdana',
					'fill' => array(
						'type' => PHPExcel_Style_Fill::FILL_SOLID,
						'color' => array('rgb' => 'FF00a0')
					)
				));
			
			$objPHPExcel->setActiveSheetIndex($counti)->setCellValue('A1', 'Selected Type Figures of vehicles in respective Battalions');
			$objPHPExcel->getActiveSheet()->getStyle('A1')->applyFromArray($titleStyle);
			$objPHPExcel->getActiveSheet()->getStyle('A1')->getAlignment()->setHorizontal(PHPExcel_Style_Alignment::HORIZONTAL_CENTER);
			//$objPHPExcel->setActiveSheetIndex($counti)->mergeCells("A1:H1");
			$row++;
			$objPHPExcel->setActiveSheetIndex($counti)->setCellValue('A'.$row,'Showing "'.$types[$selectedType].'" vehicles in '.$units[$selectedUnit]); //name of vechicel
			
			$objPHPExcel->getActiveSheet()->getStyle('A'.$row)->getAlignment()->setHorizontal(PHPExcel_Style_Alignment::HORIZONTAL_CENTER);
			$row++;
			$objPHPExcel->setActiveSheetIndex($counti)->setCellValue('A'.$row, 'S. No.'); 
			$objPHPExcel->setActiveSheetIndex($counti)->setCellValue('B'.$row, 'Vehicle Name'); 
			
			$equipmentNameStyle = array(
				'font'  => array(
					'size'  => 12,
					'name'  => 'Verdana',
					'alignment' => array(
						'horizontal' => PHPExcel_Style_Alignment::HORIZONTAL_CENTER,
					)
				));
			
			
			$cols = array('C','D','E');
			$cols_temp = array('A','B','C','D','E','F','G','H','I','J','K','L','M','N','O');
			$i=2;
			foreach($selected_battalions as $k=>$v){ 
				$objPHPExcel->setActiveSheetIndex($counti)->setCellValue($cols_temp[$i].$row, $v);
				$i++;
			}
			$objPHPExcel->setActiveSheetIndex($counti)->setCellValue($cols_temp[$i].$row, 'Total');
			$objPHPExcel->setActiveSheetIndex($counti)->mergeCells("A1:".$cols_temp[$i]."1");
			$objPHPExcel->setActiveSheetIndex($counti)->mergeCells("A".($row-1).":".$cols_temp[$i].($row-1));
			$i=0;
			$row++;
			
			$objPHPExcel->getActiveSheet()->getColumnDimension('B')->setWidth(40);
			$counter = 1;
			$objPHPExcel->getActiveSheet()
				->getStyle('A')
				->getAlignment()
				->setHorizontal(PHPExcel_Style_Alignment::HORIZONTAL_LEFT);
			$i=0;
						
			foreach($data as $vehicle_name=>$bat_data){
				$i++;
				$objPHPExcel->setActiveSheetIndex($counti)->setCellValue($cols_temp[0].$row, $i);
				$objPHPExcel->setActiveSheetIndex($counti)->setCellValue($cols_temp[1].$row, $vehicle_name);
					$j=2;
					foreach($selected_battalions as $bat_id=>$data){
						$objPHPExcel->setActiveSheetIndex($counti)->setCellValue($cols_temp[$j].$row, $bat_data[$bat_id][$selectedType]);
						$j++;
					}
				if($selectedType=="total"){
					$objPHPExcel->setActiveSheetIndex($counti)->setCellValue($cols_temp[$j].$row, $bat_data['grand_'.$selectedType]);
				}else{
					$objPHPExcel->setActiveSheetIndex($counti)->setCellValue($cols_temp[$j].$row, $bat_data['grand_total_'.$selectedType]);
				}
				$row++;
			}
			$j = 1;
			$objPHPExcel->setActiveSheetIndex($counti)->setCellValue($cols_temp[$j].$row, 'Grand Total');
			$j++;
			foreach($selected_battalions as $bat_id=>$data){
				$objPHPExcel->setActiveSheetIndex($counti)->setCellValue($cols_temp[$j].$row, $battalionGrandTotals['grand_total_'.$selectedType.$bat_id]);
				$j++;
			}
			$objPHPExcel->setActiveSheetIndex($counti)->setCellValue($cols_temp[$j].$row, $battalionGrandTotals['grand_total']);
						
			
//			// Redirect output to a client’s web browser (Excel2007)
			header('Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
			header('Content-Disposition: attachment;filename="all_vehicle_figures.xlsx"');
			header('Cache-Control: max-age=0');
			// If you're serving to IE 9, then the following may be needed
			header('Cache-Control: max-age=1');

			// If you're serving to IE over SSL, then the following may be needed
			header ('Expires: Mon, 26 Jul 1997 05:00:00 GMT'); // Date in the past
			header ('Last-Modified: '.gmdate('D, d M Y H:i:s').' GMT'); // always modified
			header ('Cache-Control: cache, must-revalidate'); // HTTP/1.1
			header ('Pragma: public'); // HTTP/1.0

			$objWriter = PHPExcel_IOFactory::createWriter($objPHPExcel, 'Excel2007');
			$objWriter->save('php://output');
			exit;
		}
		public function downloadConsolidateUnitWiseData($data,$types,$type,$vehicles,$units,$grandTotalData){
			error_reporting(0);	
			$this->load->library('excel');
			$objPHPExcel = new PHPExcel();
			$objPHPExcel->getProperties()->setCreator("ERMS-PAP")
										 ->setLastModifiedBy("ERMS-PAP")
										 ->setTitle("Office 2007 XLSX Test Document")
										 ->setSubject("Office 2007 XLSX Test Document")
										 ->setDescription("Vehicle consolidated figures, Generated by ERMS-PAP.")
										 ->setKeywords("Figures of vehicles/battalion in MT")
										 ->setCategory("Vehicle/Battalion figure view");
			$counti= 0;
			$objPHPExcel->createSheet($counti);
			$objPHPExcel->setActiveSheetIndex($counti);
			$objPHPExcel->getActiveSheet()->setTitle('Figure View'); 
			$counter = 0;
			$row=1;
			$titleStyle = array(
				'font'  => array(
					'size'  => 13,
					'name'  => 'Verdana',
					'fill' => array(
						'type' => PHPExcel_Style_Fill::FILL_SOLID,
						'color' => array('rgb' => 'FF00a0')
					)
				));
			
			$objPHPExcel->setActiveSheetIndex($counti)->setCellValue('A1', 'Consolidated Figures of  Vehicles in MT of PAP\'s,IRB\'s and CDO\'s including Training Centre\'s');
			$objPHPExcel->getActiveSheet()->getStyle('A1')->applyFromArray($titleStyle);
			$objPHPExcel->getActiveSheet()->getStyle('A1')->getAlignment()->setHorizontal(PHPExcel_Style_Alignment::HORIZONTAL_CENTER);
			//$objPHPExcel->setActiveSheetIndex($counti)->mergeCells("A1:H1");
			$row++;
			$objPHPExcel->setActiveSheetIndex($counti)->setCellValue('A'.$row,'Showing "'.$types[$type].'" vehicles.'); //name of vechicel
			
			$objPHPExcel->getActiveSheet()->getStyle('A'.$row)->getAlignment()->setHorizontal(PHPExcel_Style_Alignment::HORIZONTAL_CENTER);
			$row++;
			$objPHPExcel->setActiveSheetIndex($counti)->setCellValue('A'.$row, 'S. No.'); 
			$objPHPExcel->setActiveSheetIndex($counti)->setCellValue('B'.$row, 'Vehicle Name'); 
			
			$equipmentNameStyle = array(
				'font'  => array(
					'size'  => 12,
					'name'  => 'Verdana',
					'alignment' => array(
						'horizontal' => PHPExcel_Style_Alignment::HORIZONTAL_CENTER,
					)
				));
			
			
			$cols = array('C','D','E');
			$cols_temp = array('A','B','C','D','E','F','G','H'	);
			$i=2;
			
			unset($units['other']);
			foreach($units as $k=>$v){ 
				$objPHPExcel->setActiveSheetIndex($counti)->setCellValue($cols_temp[$i].$row, $v);
				$i++;
			}
			$objPHPExcel->setActiveSheetIndex($counti)->setCellValue($cols_temp[$i].$row, 'Total');
			$objPHPExcel->setActiveSheetIndex($counti)->mergeCells("A1:J1");
			$objPHPExcel->setActiveSheetIndex($counti)->mergeCells("A".($row-1).":".$cols_temp[$i].($row-1));
			$i=0;
			$row++;
			
			$objPHPExcel->getActiveSheet()->getColumnDimension('B')->setWidth(40);
			$counter = 1;
			$objPHPExcel->getActiveSheet()
				->getStyle('A')
				->getAlignment()
				->setHorizontal(PHPExcel_Style_Alignment::HORIZONTAL_LEFT);
			$i=0;
				//var_dump($data);
			foreach($data as $vehicle_name=>$parameters){
				$i++;
				//var_dump($parameters);
				//die;
				$objPHPExcel->setActiveSheetIndex($counti)->setCellValue($cols_temp[0].$row, $i);
				$objPHPExcel->setActiveSheetIndex($counti)->setCellValue($cols_temp[1].$row, $vehicle_name);
				//var_dump($units);
				//die;
				$j=2;
				foreach($units as $bat_id=>$data){
					$objPHPExcel->setActiveSheetIndex($counti)->setCellValue($cols_temp[$j].$row, $parameters[$bat_id][$type]);
					$j++;
				}
				if($selectedType=="total"){
					$objPHPExcel->setActiveSheetIndex($counti)->setCellValue($cols_temp[$j].$row, $parameters['grand_'.$selectedType]);
				}else{
					$objPHPExcel->setActiveSheetIndex($counti)->setCellValue($cols_temp[$j].$row, $parameters['grand_total_'.$type]);
				}
				$row++;
			}
			unset($units['other']);
			$j=1;
			$objPHPExcel->setActiveSheetIndex($counti)->setCellValue($cols_temp[$j].$row,'Grand Total');
			$j++;
			foreach($units as $k=>$unit_name){
				$objPHPExcel->setActiveSheetIndex($counti)->setCellValue($cols_temp[$j].$row,$grandTotalData['grandTotal'][$k]);
				$j++;
			}
			$objPHPExcel->setActiveSheetIndex($counti)->setCellValue($cols_temp[$j].$row, $grandTotalData['totalGrand']);
			
//			// Redirect output to a client’s web browser (Excel2007)
			header('Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
			header('Content-Disposition: attachment;filename="all_vehicle_figures.xlsx"');
			header('Cache-Control: max-age=0');
			// If you're serving to IE 9, then the following may be needed
			header('Cache-Control: max-age=1');

			// If you're serving to IE over SSL, then the following may be needed
			header ('Expires: Mon, 26 Jul 1997 05:00:00 GMT'); // Date in the past
			header ('Last-Modified: '.gmdate('D, d M Y H:i:s').' GMT'); // always modified
			header ('Cache-Control: cache, must-revalidate'); // HTTP/1.1
			header ('Pragma: public'); // HTTP/1.0

			$objWriter = PHPExcel_IOFactory::createWriter($objPHPExcel, 'Excel2007');
			$objWriter->save('php://output');
			exit;
		}
		//--------------------------Start of Updated Search functionality from previous Btalion controllers----------------------------------
		public function osi_olddataall(){ /*Osi all data*/
			$this->load->library('form_validation');
			$this->load->helper('security');
			$this->load->library('pagination');
			$this->load->helper('common');
			$this->load->model('Osi_model');
			$data['uname'] = $this->Osi_model->fetchinfo('users',array('user_log' => 4 ));		//all osi fetched	

			$ito = $this->input->get("ito",TRUE);				//battalion
			if($this->session->userdata('user_log')==4){		//battalion login
				$ito = array($this->session->userdata('userid'));
			}
			
			$mobno = $this->input->get("mobno",TRUE);
			$name = $this->input->get("name",TRUE);
			$bloodgroup = $this->input->get("bloodgroup",TRUE);
			$rcnum = $this->input->get("rcnum",TRUE);
			$RankRankre = $this->input->get("RankRankre",TRUE);
			$eor1 =  $this->input->get("eor1",TRUE);
			$eor2 =  $this->input->get("eor2",TRUE);
			$eor3 =  $this->input->get("eor3",TRUE);
			$eor4 =  $this->input->get("eor4",TRUE);
			$eor5 =  $this->input->get("eor5",TRUE);
			$postate = $this->input->get("postate",TRUE);
			$pcity = $this->input->get("pcity",TRUE);
			$stts = $this->input->get("stts",TRUE);
			$classes = $this->input->get('classes',TRUE);
			$UnderGraduate = $this->input->get("UnderGraduate",TRUE);
			$Graduate = $this->input->get("Graduate",TRUE);
			$PostGraduate = $this->input->get("PostGraduate",TRUE);
			$Doctorate = $this->input->get("Doctorate",TRUE);
			$gender = $this->input->get("gender",TRUE);
			$single =  $this->input->get("single",TRUE);
			$Modemdr = $this->input->get("Modemdr",TRUE);
			$Rankre = $this->input->get("Rankre",TRUE);
			$Enlistmentec = $this->input->get("Enlistmentec",TRUE);
			$InductionModeim = $this->input->get("InductionModeim",TRUE);
			$clit = $this->input->get("clit",TRUE);
			$dateofesnlistment1 = $this->input->get("dateofesnlistment1",TRUE);
			$dateofesnlistment2 =  $this->input->get("dateofesnlistment2",TRUE);
			$NamesofsCourses =  $this->input->get("NamesofsCourses1",TRUE);
			$NamesofsCourses2 =  $this->input->get("NamesofsCourses2",TRUE);
			$DateofRetirementdor = $this->input->get("DateofRetirementdor",TRUE);
			$dateofbirth = $this->input->get("dateofbirth",TRUE);
			$dateofbirthi = $this->input->get("dateofbirthi",TRUE);
			$dateofbirthi = $this->input->get("dateofbirthi",TRUE);
			$height = $this->input->get("height",TRUE);
			$inch = $this->input->get("inch",TRUE);
			$Postingtiset = $this->input->get("Postingtiset",TRUE);
			$Postingtiset2 = $this->input->get("Postingtiset2",TRUE);
			$Postingtiset3 = $this->input->get("Postingtiset3",TRUE);
			$Postingtiset4 = $this->input->get("Postingtiset4",TRUE);
			$Postingtiset5 = $this->input->get("Postingtiset5",TRUE);
			$Postingtiset6 = $this->input->get("Postingtiset6",TRUE);
			$Postingtiset7 = $this->input->get("Postingtiset7",TRUE);
			$Postingtiset8 = $this->input->get("Postingtiset8",TRUE);
			$Postingtiset9 = $this->input->get("Postingtiset9",TRUE);
			$p = '';

			
			$weapon = $this->Osi_model->get_users_countosiall($ito,$name,$bloodgroup,$rcnum,$RankRankre,$eor1,$eor2,$eor3,$eor4,$eor5,$postate,$pcity,$stts,$UnderGraduate,$Graduate,$PostGraduate,$Doctorate,$gender,$single,$Modemdr,$Rankre,$Enlistmentec,$InductionModeim,$clit,$dateofesnlistment1,$dateofesnlistment2,$NamesofsCourses,$NamesofsCourses2,$DateofRetirementdor,$dateofbirth,$dateofbirthi,$height,$inch,$Postingtiset,$Postingtiset2,$Postingtiset3,$Postingtiset4,$Postingtiset5,$Postingtiset6,$Postingtiset7,$Postingtiset8,$Postingtiset9,$p,$mobno,$classes);
			
			$data['statelist'] = $this->Osi_model->fetchinfo('state_list',array('state_status' => 1 ));

			$config = array();
			$config["base_url"] = base_url() . "bt-osi-oldall2";
			$config["total_rows"] = $weapon;
			$download = $this->input->get('download');
			if($download=='download'){
				$config["per_page"] = $weapon;
			}else{
				$config["per_page"] = 100;
			}
			$config['use_page_numbers'] = TRUE;
			$config['reuse_query_string'] = TRUE;
			$config['full_tag_open'] = "<ul class='pagination'>";
			$config['full_tag_close'] ="</ul>";
			$config['num_tag_open'] = '<li>';
			$config['num_tag_close'] = '</li>';
			$config['cur_tag_open'] = "<li class='disabled'><li class='active'><a href='#'>";
			$config['cur_tag_close'] = "<span class='sr-only'></span></a></li>";
			$config['next_tag_open'] = "<li>";
			$config['next_tagl_close'] = "</li>";
			$config['prev_tag_open'] = "<li>";
			$config['prev_tagl_close'] = "</li>";
			$config['first_tag_open'] = "<li>";
			$config['first_tagl_close'] = "</li>";
			$config['last_tag_open'] = "<li>";
			$config['last_tagl_close'] = "</li>";

        	$this->pagination->initialize($config);
			$data["links"] = $this->pagination->create_links();
			$page = ($this->uri->segment(2)) ? $this->uri->segment(2) : 1;
			$start = ($page-1)*$config["per_page"];
			//echo $start; die();
			//print_r($data["links"]); die();

		
			
			$data["weapon"] = $this->Osi_model->get_usersosiall($ito,$name,$bloodgroup,$rcnum,$RankRankre,$eor1,$eor2,$eor3,$eor4,$eor5,$postate,$pcity,$stts,$UnderGraduate,$Graduate,$PostGraduate,$Doctorate,$gender,$single,$Modemdr,$Rankre,$Enlistmentec,$InductionModeim,$clit,$dateofesnlistment1,$dateofesnlistment2,$NamesofsCourses,$NamesofsCourses2,$DateofRetirementdor,$dateofbirth,$dateofbirthi,$height,$inch,$Postingtiset,$Postingtiset2,$Postingtiset3,$Postingtiset4,$Postingtiset5,$Postingtiset6,$Postingtiset7,$Postingtiset8,$Postingtiset9,$p,$config["per_page"],$start,$mobno,$classes);
			//var_dump($data['weapon']);
			//echo $this->db->last_query();
			//die;
			$data["counts"] = $this->Osi_model->get_users_countosiall($ito,$name,$bloodgroup,$rcnum,$RankRankre,$eor1,$eor2,$eor3,$eor4,$eor5,$postate,$pcity,$stts,$UnderGraduate,$Graduate,$PostGraduate,$Doctorate,$gender,$single,$Modemdr,$Rankre,$Enlistmentec,$InductionModeim,$clit,$dateofesnlistment1,$dateofesnlistment2,$NamesofsCourses,$NamesofsCourses2,$DateofRetirementdor,$dateofbirth,$dateofbirthi,$height,$inch,$Postingtiset,$Postingtiset2,$Postingtiset3,$Postingtiset4,$Postingtiset5,$Postingtiset6,$Postingtiset7,$Postingtiset8,$Postingtiset9,$p,$mobno,$classes);
			//die;
			//echo '<HR>';
			//echo $this->db->last_query();
				$data['nm'] = $NamesofsCourses.$NamesofsCourses2;
			$this->form_validation->set_rules("BattalionUnitito", "BattalionUnitito", "trim");
			//die;
			if ($this->form_validation->run()){
				//die;
				
				$data["weapon"] = $this->Osi_model->get_usersosiall($ito,$name,$bloodgroup,$rcnum,$RankRankre,$eor1,$eor2,$eor3,$eor4,$eor5,$postate,$pcity,$stts,$UnderGraduate,$Graduate,$PostGraduate,$Doctorate,$gender,$single,$Modemdr,$Rankre,$Enlistmentec,$InductionModeim,$clit,$dateofesnlistment1,$dateofesnlistment2,$NamesofsCourses,$NamesofsCourses2,$DateofRetirementdor,$dateofbirth,$dateofbirthi,$height,$inch,$Postingtiset,$Postingtiset2,$Postingtiset3,$Postingtiset4,$Postingtiset5,$Postingtiset6,$Postingtiset7,$Postingtiset8,$Postingtiset9,$p,$config["per_page"],$start,$mobno,$classes);
				
				//echo $this->db->last_query();
				
			$data["counts"] = $this->Osi_model->get_users_countosiall($ito,$name,$bloodgroup,$rcnum,$RankRankre,$eor1,$eor2,$eor3,$eor4,$eor5,$postate,$pcity,$stts,$UnderGraduate,$Graduate,$PostGraduate,$Doctorate,$gender,$single,$Modemdr,$Rankre,$Enlistmentec,$InductionModeim,$clit,$dateofesnlistment1,$dateofesnlistment2,$NamesofsCourses,$NamesofsCourses2,$DateofRetirementdor,$dateofbirth,$dateofbirthi,$height,$inch,$Postingtiset,$Postingtiset2,$Postingtiset3,$Postingtiset4,$Postingtiset5,$Postingtiset6,$Postingtiset7,$Postingtiset8,$Postingtiset9,$p,$mobno,$classes);
				$data['nm'] = $NamesofsCourses.$NamesofsCourses2;	
			}
			$data['name'] ='';
			//echo $this->db->last_query();
			//echo 'dalwinder';
			
			if($download=='download'){
				$this->download_users_excel($data["weapon"]);
			}
			$this->load->view('Osi/search/search',$data);
		}
		/*
			Here we download the excel of all the fetched records
		*/
		public function download_users_excel($users){
			
			error_reporting(E_ALL);	
			$this->load->library('excel');
			$objPHPExcel = new PHPExcel();
			$objPHPExcel->getProperties()->setCreator("ERMS-PAP")
										 ->setLastModifiedBy("ERMS-PAP")
										 ->setTitle("Office 2007 XLSX Test Document")
										 ->setSubject("Office 2007 XLSX Test Document")
										 ->setDescription("Vehicle consolidated figures, Generated by ERMS-PAP.")
										 ->setKeywords("Figures of vehicles/battalion in MT")
										 ->setCategory("Vehicle/Battalion figure view");
			$counti= 0;
			$objPHPExcel->createSheet($counti);
			$objPHPExcel->setActiveSheetIndex($counti);
			$objPHPExcel->getActiveSheet()->setTitle('Figure View'); 
			$counter = 0;
			$row=1;
			$titleStyle = array(
				'font'  => array(
					'size'  => 13,
					'name'  => 'Verdana',
					'fill' => array(
						'type' => PHPExcel_Style_Fill::FILL_SOLID,
						'color' => array('rgb' => 'FF00a0')
					)
				));
			
			
			$objPHPExcel->setActiveSheetIndex($counti)->setCellValue('A'.$row, 'S. No.'); 
			$objPHPExcel->setActiveSheetIndex($counti)->setCellValue('B'.$row, 'Battalion/Unit'); 
			$objPHPExcel->setActiveSheetIndex($counti)->setCellValue('C'.$row, 'Name'); 
			$objPHPExcel->setActiveSheetIndex($counti)->setCellValue('D'.$row, 'Present Rank'); 
			$objPHPExcel->setActiveSheetIndex($counti)->setCellValue('E'.$row, 'Dept. No.'); 
			$objPHPExcel->setActiveSheetIndex($counti)->setCellValue('F'.$row, 'District'); 
			$objPHPExcel->setActiveSheetIndex($counti)->setCellValue('G'.$row, 'Gender'); 
			$objPHPExcel->setActiveSheetIndex($counti)->setCellValue('H'.$row, 'Marital Status'); 
			$objPHPExcel->setActiveSheetIndex($counti)->setCellValue('I'.$row, 'Date of Birth'); 
			$objPHPExcel->setActiveSheetIndex($counti)->setCellValue('J'.$row, 'Date of Enlistment'); 
			$objPHPExcel->setActiveSheetIndex($counti)->setCellValue('K'.$row, 'Date of Retirement'); 
			$objPHPExcel->setActiveSheetIndex($counti)->setCellValue('L'.$row, 'Caste'); 
			$objPHPExcel->setActiveSheetIndex($counti)->setCellValue('M'.$row, 'Category'); 
			$objPHPExcel->setActiveSheetIndex($counti)->setCellValue('N'.$row, 'Phone 1'); 
			$objPHPExcel->setActiveSheetIndex($counti)->setCellValue('O'.$row, 'Blood Group'); 
			$objPHPExcel->setActiveSheetIndex($counti)->setCellValue('P'.$row, 'Education Qualified'); 
			$objPHPExcel->setActiveSheetIndex($counti)->setCellValue('Q'.$row, 'Computer Literate'); 
			$objPHPExcel->setActiveSheetIndex($counti)->setCellValue('R'.$row, 'Qualified Courses'); 
			$objPHPExcel->setActiveSheetIndex($counti)->setCellValue('S'.$row, 'Courses Name'); 
			
			
			$objPHPExcel->setActiveSheetIndex($counti)->setCellValue('T'.$row, 'Bank Account No.'); 
			$objPHPExcel->setActiveSheetIndex($counti)->setCellValue('U'.$row, 'Height'); 
			$objPHPExcel->setActiveSheetIndex($counti)->setCellValue('V'.$row, 'GPF Pol No./PRAN No.'); 
			$objPHPExcel->setActiveSheetIndex($counti)->setCellValue('W'.$row, 'Good Entries'); 
			$objPHPExcel->setActiveSheetIndex($counti)->setCellValue('X'.$row, 'Bad Entries'); 
			$objPHPExcel->setActiveSheetIndex($counti)->setCellValue('Y'.$row, 'Posting Detail'); 
			$objPHPExcel->setActiveSheetIndex($counti)->setCellValue('Z'.$row, 'Date of posting'); 
			
			$equipmentNameStyle = array(
				'font'  => array(
					'size'  => 12,
					'name'  => 'Verdana',
					'alignment' => array(
						'horizontal' => PHPExcel_Style_Alignment::HORIZONTAL_CENTER,
					)
				));
			
			
			$cols = array('C','D','E');
			$cols_temp = array('A','B','C','D','E','F','G','H'	);
			$i=2;
			$counter = 0;
			
			foreach($users as $k=>$user){
				$row++;
				$counter++;
				$objPHPExcel->setActiveSheetIndex($counti)->setCellValue('A'.$row, $counter); 
				if($user->bunitdistrict ==''){
					$bats = fetchoneinfo('users',array('users_id' => $user->bat_id));
					if(isset($bats->nick)){
						$objPHPExcel->setActiveSheetIndex($counti)->setCellValue('B'.$row, $bats->nick); 
					}
				}else{
					$objPHPExcel->setActiveSheetIndex($counti)->setCellValue('B'.$row, $user->bunitdistrict ); 
					
				} 
				$objPHPExcel->setActiveSheetIndex($counti)->setCellValue('C'.$row, $user->name); 
				$objPHPExcel->setActiveSheetIndex($counti)->setCellValue('D'.$row,$user->cexrank.$user->cminirank.$user->cmedirank.$user->ccprank.$user->cccrank);
				$objPHPExcel->setActiveSheetIndex($counti)->setCellValue('E'.$row,$user->depttno);
				$objPHPExcel->setActiveSheetIndex($counti)->setCellValue('F'.$row,$user->district);
				$objPHPExcel->setActiveSheetIndex($counti)->setCellValue('G'.$row,$user->gender);
				$objPHPExcel->setActiveSheetIndex($counti)->setCellValue('H'.$row,$user->maritalstatus);
				$db =  date('d-m-Y',strtotime($user->dateofbith)); if($db == '01-01-1970'){$date= '-';}else{$date = $db;}
				$objPHPExcel->setActiveSheetIndex($counti)->setCellValue('I'.$row,$date);
				$dde =  date('d-m-Y',strtotime($user->dateofinlitment)); if($dde == '01-01-1970'){$date2 = '-';}else{ $date2 = $dde;}
				$objPHPExcel->setActiveSheetIndex($counti)->setCellValue('J'.$row,$date2);
				$objPHPExcel->setActiveSheetIndex($counti)->setCellValue('K'.$row,$user->dateofretirment);
				$objPHPExcel->setActiveSheetIndex($counti)->setCellValue('L'.$row,$user->caste);
				$objPHPExcel->setActiveSheetIndex($counti)->setCellValue('M'.$row,$user->category);
				$objPHPExcel->setActiveSheetIndex($counti)->setCellValue('N'.$row,$user->phono1);
				$objPHPExcel->setActiveSheetIndex($counti)->setCellValue('O'.$row,$user->bloodgroup);
				$objPHPExcel->setActiveSheetIndex($counti)->setCellValue('P'.$row,$user->eduqalification.' '.$user->UnderGraduate.$user->Graduate.$user->PostGraduate.$user->Doctorate.$user->Doctorateother);
				$objPHPExcel->setActiveSheetIndex($counti)->setCellValue('Q'.$row,$user->comlit);
				$ax = explode('@', $user->NamesofsCourses);
				$objPHPExcel->setActiveSheetIndex($counti)->setCellValue('R'.$row,count($ax));
				//$objPHPExcel->setActiveSheetIndex($counti)->setCellValue('R'.$row,$nm);
				
				//$objPHPExcel->setActiveSheetIndex($counti)->setCellValue('S'.$row,$user->courseName);
				$objPHPExcel->setActiveSheetIndex($counti)->setCellValue('T'.$row,$user->bankacno);
				$objPHPExcel->setActiveSheetIndex($counti)->setCellValue('U'.$row,$user->feet.'"'.' '.$user->inch.'"');
				$objPHPExcel->setActiveSheetIndex($counti)->setCellValue('V'.$row,$user->gpfpranno.' '.$user->PRAN);
				$objPHPExcel->setActiveSheetIndex($counti)->setCellValue('W'.$row,$user->gd1);
				$objPHPExcel->setActiveSheetIndex($counti)->setCellValue('X'.$row,$user->bd1);
				/*$pos = fetchoneinfodesc('newosip',array('man_id' => $user->man_id ),'man_id');
				 if($pos !=''){ 
					$objPHPExcel->setActiveSheetIndex($counti)->setCellValue('Y'.$row,$pos->fone1.$pos->vploc.$pos->vpdis.$pos->fone2.$pos->noj.$pos->jsdis.$pos->fone3.$pos->fone3.$pos->fone4.$pos->fone5.$pos->osgloc.$pos->osgdis.$pos->fone6.$pos->fone7.$pos->fone8.$pos->fone9.$pos->bsdnob.$pos->bsddis.$pos->bsdloc.$pos->fone10.$pos->fone11.$pos->fone12.$pos->lone1.$pos->perdupod.$pos->perdudis.$pos->perduorno.$pos->perduordate.$pos->lone2.$pos->dgppod.$pos->dgpdis.$pos->dgporno.$pos->dgpordate.$pos->lone3.$pos->tertdpod.$pos->tertddis.$pos->tertdorno.$pos->tertdordate.$pos->sqone1.$pos->sqone2.$pos->sqone3.$pos->sqone4.$pos->sqone5.$pos->sstgpod.$pos->sstgdis.$pos->sstgorno.$pos->sstgordate.$pos->sqone6.$pos->sqone6.$pos->sqone7.$pos->swatpod.$pos->swatdis.$pos->swatorno.$pos->swatordate.$pos->paone1.$pos->paone2.$pos->awdpmpod.$pos->awdpmorno.$pos->awdpmordate.$pos->paone3.$pos->awdpfpod.$pos->awdpforno.$pos->awdpfordate.$pos->paone4.$pos->awdpompod.$pos->awdpomorno.$pos->awdpomordate.$pos->paone5.$pos->awdpofpod.$pos->awdpoforno.$pos->awdpofordate.$pos->paone6.$pos->paone7.$pos->paone8.$pos->paone9.$pos->paone10.$pos->paone11.$pos->paone12.$pos->paone13.$pos->paone14.$pos->paone15.$pos->paone16.$pos->paone17.$pos->paone18.$pos->paone19.$pos->paone20.$pos->paone21.$pos->paone22.$pos->paone23.$pos->paone24.$pos->ssone23.$pos->dsopod.$pos->dsoorno.$pos->dsoordate.$pos->ssone24.$pos->csojalorno.$pos->csojalordate.$pos->ssone25.$pos->mispatorno.$pos->mispatordate.$pos->ssone26.$pos->othersnod.$pos->othersnodis.$pos->othersorno.$pos->othersordate.$pos->awbone1.$pos->awbone2.$pos->pssawonof.$pos->pssaworank.$pos->pssawoordate.$pos->awbone3.$pos->osihonoo.$pos->awbone4.$pos->Readerosinbo.$pos->Orderly.$pos->telopr.$pos->darrun.$pos->awbone5.$pos->bnkgdop.$pos->awbone6.$pos->bhogpog.$pos->bhogdop.$pos->awbone7.$pos->tradestot.$pos->tradestt.$pos->tradesbat.$pos->tradesdop.$pos->tradesorno.$pos->awbone8.$pos->mtsecpod.$pos->mtsecvehno.$pos->mtsecdop.$pos->mtsecorno.$pos->awbone9.$pos->quartbradop.$pos->quartbraorno.$pos->awbone10.$pos->awbone11.$pos->awbone12.$pos->awbone12.$pos->recrutnorb.$pos->recrutorno.$pos->recrutordate.$pos->bmdone1.$pos->bmdone2.$pos->leavefrom.$pos->leaveto.$pos->bmdone3.$pos->absentfrom.$pos->absentddr.$pos->absentdate.$pos->bmdone4.$pos->usdos.$pos->usros.$pos->bmdone5.$pos->bmdone6.$pos->bmdone7.$pos->bmdone8.$pos->bmdone9.$pos->bmdone10.$pos->instone1.$pos->instone2.$pos->instone3.$pos->instone4.$pos->traning1.$pos->traning2.$pos->traning3.$pos->btarin1.$pos->btarin2.$pos->btarin3.$pos->btarin4.$pos->btarin5.$pos->btarin6.$pos->btarin7.$pos->btarin8.$pos->btarin9.$pos->btarin10.$pos->cfpop.$pos->cfppd.$pos->cfpdop.$pos->cfpdop);
				
					$objPHPExcel->setActiveSheetIndex($counti)->setCellValue('Z'.$row,$pos->dateofposting1);
				 }*/
				 $objPHPExcel->setActiveSheetIndex($counti)->setCellValue('Y'.$row,trim($user->posting_concat1));
				 $objPHPExcel->setActiveSheetIndex($counti)->setCellValue('Z'.$row,$user->dateofposting1);
			}
			
//			// Redirect output to a client’s web browser (Excel2007)
			header('Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
			header('Content-Disposition: attachment;filename="employees.xlsx"');
			header('Cache-Control: max-age=0');
			// If you're serving to IE 9, then the following may be needed
			header('Cache-Control: max-age=1');

			// If you're serving to IE over SSL, then the following may be needed
			header ('Expires: Mon, 26 Jul 1997 05:00:00 GMT'); // Date in the past
			header ('Last-Modified: '.gmdate('D, d M Y H:i:s').' GMT'); // always modified
			header ('Cache-Control: cache, must-revalidate'); // HTTP/1.1
			header ('Pragma: public'); // HTTP/1.0

			$objWriter = PHPExcel_IOFactory::createWriter($objPHPExcel, 'Excel2007');
			$objWriter->save('php://output');
			exit;
		}
		public function allOsiBattalion(){
			
		}

		//--------------------------End of Updated Search functionality from previous----------------------------------
	}
