<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="shortcut icon" href="<?php echo base_url(); ?>webroot/images/favicon.png" type="image/png">
    <title>Practice Ammuniation Report</title>
    <link rel="stylesheet" href="<?php echo base_url(); ?>webroot/css/style.default.css" />
          <script>
            function myFunction() {
                window.print();
            }
          </script>
</head>
<body>
    <h3 class="text-center">STATEMENT  OF PRACTICE AMMUNITION <?php $val = explode(' ', $this->session->userdata('nick')); echo $val[0];  ?> <?php $val = explode(' ', $this->session->userdata('nick2')); echo $val[0];  ?> ON <?php echo strtoupper(date('d-m-Y h:i:s a')); ?></h3> 
    <form method="post" style="float:right;padding-right:10%;">
        <?php 
        $checked = true;
        $data = ['name'=>'skip_zero','checked'=>$skip_zero,'value'=>'skip_zero','id'=>'skip_zero'];
        echo form_checkbox($data); 
        echo form_label('Skip Zero','',['for'=>'skip_zero']);
        ?>
        <input type="submit" name="submit" class="btn btn-primary btn-sm">
    </form><br><br><br>
            <div class="row">
        <div class="col-sm-10 col-xs-offset-1">
            <table class="table  table-bordered">
              <thead>
                 <tr>
                 <th>Sr No.</th>
                    <th>Detail of Arms </th>
                    <th>Detail of Bore</th>
                    <th>Sanctioned</th>
                     <th>Holding</th>
                      <th>Issued</th>
                      <th>Balance In Kot</th>
                      <th>Remarks</th>
                 </tr>
              </thead>
              <tbody>
                <?php  
                if($new_data!=null){$count=0;
                    foreach($new_data as $k=>$value){ $count++;?>
                        <tr class="odd gradeX">
                 <td><?php echo $count;  ?></td>
                    <td><?php echo $value->arm;  ?></td>
                    <td><?php echo $value->bore;  ?></td>
                    <td><?php echo $value->sun;  ?></td>
                    <td><?php echo $value->qty;  ?></td>
                    <td><?php echo $value->issued;  ?></td>
                    <td><?php echo ($value->qty-$value->issued);  ?></td>
                    <td><?php echo $value->remarkwep;  ?></td>
                    <?php if(false){ ?>
                    <td><?php  if($issued!=''){echo $issued->sun;}else{echo "-";}  ?></td>
                     <td><?php  if($hold!=''){echo $hol =  $hold->qty + $hold->issued;}else{echo "-";};  ?> </td>
                    <td><?php if($hold!=''){echo $hold->issued;}else{echo "-";} ?> </td>
                    <td> <?php if($hold!=''){echo $hold->qty;}else{echo "-";} ?></td>
                    <td><?php if($issued!=''){echo $issued->remarkwep;}else{echo "-";}  ?></td></tr> <?php }
                    }
                }
                if(isset($msk) && $msk!=''){ $count = 0; foreach($msk as $value): 
                $issued = info_fetch_ammucountpi($value->bore,$value->arm,$ninfo); 
                $hold = fetchoneinfoammu('newwepon_dataqtyp',array('bore' => $value->bore , 'arm' => $value->arm, 'bat_id' => $ninfo));
                if( !$skip_zero || (null!=$issued && $issued->sun>0) || (null!=$hold && (($hold->qty+$hold->issued)>0 || $hold->qty>0 || $hold->issued>0) ) ) :
                    $count = $count + 1;    
                ?>
                  
                <tr class="odd gradeX">
                 <td><?php echo $count;  ?></td>
                    <td><?php echo $value->arm;  ?></td>
                    <td><?php  if($issued!=''){echo $issued->sun;}else{echo "-";}  ?></td>
                     <td><?php  if($hold!=''){echo $hol =  $hold->qty + $hold->issued;}else{echo "-";};  ?> </td>
                    <td><?php if($hold!=''){echo $hold->issued;}else{echo "-";} ?> </td>
                    <td> <?php if($hold!=''){echo $hold->qty;}else{echo "-";} ?></td>
                    <td><?php if($issued!=''){echo $issued->remarkwep;}else{echo "-";}  ?></td></tr>
                <?php endif; ?>
                    <?php endforeach; } ?>
              </tbody>
              <tfoot>
                <tr>
                    <td colspan="14">Report generated by: <strong><?php $val = explode(' ', $this->session->userdata('nick')); echo $val[0];  ?> <?php $val = explode(' ', $this->session->userdata('nick2')); echo $val[0];  ?></strong> <span class="pull-right">Date: <strong><?php echo date('d-m-Y h:i:A'); ?></strong></span></td>
                </tr>
              </tfoot>
           </table>
           </div></div>
</body>
</html>